SFDigitalServices/sfgov

- README.md
updated README.md with PR workflow documentation
> document pr workflow

- README.md
> emphasize branches instead of forks

- config/core.extension.yml
There's no configuration yet. What's needed on that front is still being worked out.
> [SG-6] Enable some Metatag submodules.

- composer.json
- composer.lock
- config/core.extension.yml
> Adminimal Admin Toolbar

- .gitignore
> Ignore Lando config

- config/core.base_field_override.node.department.promote.yml
- config/core.base_field_override.node.department.title.yml
- config/core.entity_form_display.node.department.default.yml
- config/core.entity_view_display.node.department.default.yml
- config/core.entity_view_display.node.department.teaser.yml
- config/field.field.node.department.field_department_code.yml
- config/field.field.node.department.field_go_to_current_url.yml
- config/field.field.node.department.field_image.yml
- config/field.field.node.department.field_mission.yml
- config/field.field.node.department.field_parent_department.yml
- config/field.field.node.department.field_public_body.yml
- config/field.field.node.department.field_url.yml
- config/field.storage.node.field_department_code.yml
- config/field.storage.node.field_go_to_current_url.yml
- config/field.storage.node.field_mission.yml
- config/field.storage.node.field_parent_department.yml
- config/field.storage.node.field_public_body.yml
- config/field.storage.node.field_url.yml
- config/language.content_settings.node.department.yml
- config/node.type.department.yml
Adds the _department_ content type and it's configuration.
> [SG-87] Department homepages nodes.

- .gitignore
- composer.json
- composer.lock
I'll setup Asset Packagist in a separate PR, since it's not really related.
> Add SFGov Pattern Lab via Composer

- composer.lock
`composer update --lock` probably was not run.
> Lock file updates

- config/core.entity_view_display.paragraph.section.default.yml
- config/system.site.yml
- tests/features/content.feature
- web/themes/custom/sfgovpl/README.md
- web/themes/custom/sfgovpl/templates/field/field--paragraph--field-link--section.html.twig
> [SG-169] - updated field paragraph

- config/core.entity_form_display.paragraph.phone.default.yml
- config/core.entity_view_display.paragraph.phone.default.yml
- config/field.field.paragraph.phone.field_tel.yml
Field ordering, label visibility.
> [SG-104] Phone number paragraph form and display config

- README.md
- composer.json
- composer.lock
- config/language.negotiation.yml
A few minor edits to the README.
Installed Mandrill module for outgoing emails.
> Sg 172 mandrill

- config/core.entity_form_display.node.transaction.default.yml
- config/core.entity_view_display.node.transaction.default.yml
- config/core.entity_view_display.node.transaction.teaser.yml
- config/field.field.node.transaction.field_topics.yml
- config/field.field.node.transaction.field_transactions.yml
- config/field.storage.node.field_topics.yml
- config/field.storage.node.field_transactions.yml
.. and move Topic to the bottom of the form, as requested.
> [SG-10] Rename topic and transaction field/labels.

- composer.json
- composer.lock
- web/themes/custom/sfgovpl/sfgovpl.info.yml
- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
- web/themes/custom/sfgovpl/templates/block/block--sfgovpl-main-menu.html.twig
- web/themes/custom/sfgovpl/templates/layout/page.html.twig
this PR makes the main menu reponsive
> Sg 170 reponsive mobile menu

- composer.json
- composer.lock
- config/core.extension.yml
Add the Autodrop module and enable it.
> Sg 183 add widget

- web/themes/custom/sfgovpl/templates/eck/eck-entity--location--physical--search-index.html.twig
- web/themes/custom/sfgovpl/templates/eck/eck-entity--location--physical.html.twig
The references to remove field broke search.
> remove theme references to the removed field_directions_link

- config/core.entity_view_display.node.department.search_index.yml
- web/themes/custom/sfgovpl/templates/node/node--transaction--search-index.html.twig
- fix phone icon in search results
- fix dept name to display only in search results
> Tx listings

- .gitignore
- web/robots.txt
update robots.txt to disallow all
> add robots.txt and disallow all

- config/core.entity_view_display.node.department.search_index.yml
- web/themes/custom/sfgovpl/templates/node/node--transaction--search-index.html.twig
only display in search results
> do not display related dept on transaction list pages

- config/block.block.thiswebsiteisinprogress.yml
- config/core.entity_form_display.node.page.default.yml
- config/core.entity_view_display.node.page.default.yml
- config/field.field.node.page.field_content_bottom.yml
- config/field.storage.node.field_content_bottom.yml
- config/simple_block.simple_block.new_website_san_francisco.yml
- config/simple_block.simple_block.website_in_progress_departments.yml
- web/themes/custom/sfgovpl/templates/node/node--page--full.html.twig
- update link and add period
- create content bottom field for basic pages, display if exists
- todo on production: remove new website block from field_content on contact-us basic page add it to field_content_bottom
> New website block

- web/themes/custom/sfgovpl/templates/node/node--transaction--search-index.html.twig
some of the transactions were missing related depts - suspect that it may have been because of some weird indexing thing.  looping through the array of related depts instead of grabbing whatever is at index 0.
> Sg 315 search related depts

- web/themes/custom/sfgovpl/package-lock.json
- web/themes/custom/sfgovpl/package.json
Current version of hoek has a vulnerability. Updating actually seems to remove it as a dependency.
Reran gulp after this update and nothing seemed to change.
> Update package.json in sfgovpl

- README.md
just a (hopefully) helpful lando pull additional info
> add info about lando pull options to skip prompts

- tests/features/sfgov.feature
added this test to existing test
> SG-308 add test for redirect when transaction has direct external url

- pantheon.yml
- web/private/scripts/slack-notify/slack_notify_drush_site_audit.php
want to try out slack notifications for pantheon deploys
> add slack notification for deploy

- config/block.block.sfgovpl_page_title.yml
- config/core.entity_view_display.node.person.default.yml
- web/modules/custom/sfgov_event_subscriber/src/EventSubscriber/RedirectEventSubscriber.php
- web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig
basic styling for the person page
> Sg 356 person page

- tests/features/sfgov.feature
- web/robots.txt
- web/themes/custom/sfgovpl/sfgovpl.theme
insert meta tags for departments and transactions for use with 311 search
> Sg 369 custom meta tags

- composer.json
- composer.lock
> core update 8.6.3, exclude robots.txt from drupal-scaffold

- .lando.yml
- README.md
- composer.json
- composer.lock
had to downgrade drush to 8.1.16 - was throwing up trying to connect to db and running config export/import.  should hopefully only impact local dev
> Lando drush issues

- web/robots.txt
added motionpoint's crawlers' user agents
> allow motion point crawl

- web/modules/custom/sfgov_utilities/sfgov_utilities.module
> sg-443 add condition to check for null related dept

- tests/features/sfgov.feature
- web/themes/custom/sfgovpl/includes/form.inc
- web/themes/custom/sfgovpl/sfgovpl.theme
- web/themes/custom/sfgovpl/src/js/search.js
sf.gov has a bug on the search page:
https://sf.gov/search?keyword=birth
> Sg 477 translation search block

- composer.json
- composer.lock
updates modules metatag and paragraph
> Core 8.6.10

- .lando.yml
- README.md
update lando.yml for 3.0.0-RC.2+
> Lando update

- web/themes/custom/sfgovpl/dist/css/drupal.css
The previous PR was missing the compiled CSS.
> SG-571 - Position tweaks css.

- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
- web/themes/custom/sfgovpl/src/js/navigation.js
- web/themes/custom/sfgovpl/src/js/uswds-modified.js
- Removed  pattern lab uswds.js file put it in the theme and modified it there.
> 571 mobile search e

- config/workflows.workflow.editorial.yml
- tests/features/sfgov.feature
also add workflow to basic page and person
> Sg 607 info page drafts

- web/themes/custom/sfgovpl/src/js/translate.js
> for...of not supported in ie

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-3elected.scss
had to account for last people section
> Sg 697 city officials

- web/modules/custom/sfgov_search/src/Form/SearchForm.php
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/js/translate.js
- web/themes/custom/sfgovpl/src/sass/block/_block-search.scss
- web/themes/custom/sfgovpl/src/sass/components/_gtranslate.scss
- web/themes/custom/sfgovpl/templates/block/block--gtranslate-block.html.twig
For context: https://sfgovdt.jira.com/browse/SG-334
search form: added form and input aria attributes, label for input
translate dropdown: added aria attributes, label for dropdown
> Sg 334 form accessibility

- .circleci/config.yml
- .circleci/scripts/ghost-inspector/run-gi-suite
- Removed command to run behat tests in `.circleci/config.yml`
- Added script to trigger ghost inspector test suite for pantheon env via ghost inspector api
> Sg 731 ci gi integration

- config/core.entity_form_display.paragraph.email_addresses.default.yml
- config/core.entity_form_display.paragraph.phone_numbers.default.yml
- config/core.entity_view_display.paragraph.email_addresses.default.yml
- config/core.entity_view_display.paragraph.phone_numbers.default.yml
- config/field.field.node.transaction.field_help.yml
- config/field.field.paragraph.email_addresses.field_email_addresses_email.yml
- config/field.field.paragraph.phone_numbers.field_phone_numbers_phone.yml
- config/field.storage.paragraph.field_email_addresses_email.yml
- config/field.storage.paragraph.field_phone_numbers_phone.yml
- config/paragraphs.paragraphs_type.email_addresses.yml
- config/paragraphs.paragraphs_type.phone_numbers.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/_mixins-fs.scss
- web/themes/custom/sfgovpl/src/sass/components/_email.scss
- web/themes/custom/sfgovpl/src/sass/components/_phone.scss
- web/themes/custom/sfgovpl/src/sass/drupal.scss
- web/themes/custom/sfgovpl/src/sass/node/_node-transaction-help.scss
- web/themes/custom/sfgovpl/templates/components/email.twig
- web/themes/custom/sfgovpl/templates/components/phone.twig
- web/themes/custom/sfgovpl/templates/field/field--paragraph--email.html.twig
- web/themes/custom/sfgovpl/templates/field/field--paragraph--phone.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--email--default.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--email.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--phone--default.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--phone.html.twig
- Added two new paragraphs: Email addresses and Phone numbers, each containing paragraphs email address and phone number, respectively.
- Added twig components and related css for each added paragraph
- Exported config for new paragraphs
- tabs to spaces and typo cleanup
> Sg 578 group tx help

- config/sfgov_search.settings.yml
- web/modules/custom/sfgov_search/config/install/sfgov_search.settings.yml
- web/modules/custom/sfgov_search/js/sfgov_search.js
- web/modules/custom/sfgov_search/src/Form/SearchForm.php
- web/modules/custom/sfgov_search/src/Form/SfGovSearchConfigurationForm.php
- add qie (funnelback domain influencer) to search request
- add qie to drupal sfgov search module configuration form
> Sg 726 search priortization

- web/themes/custom/sfgovpl/README.md
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/sfgovpl.info.yml
- web/themes/custom/sfgovpl/src/sass/components/_alert.scss
- web/themes/custom/sfgovpl/src/sass/components/_header.scss
https://sfgovdt.jira.com/browse/SG-747
Also removed a reference to a template file that no longer exists and added a minor update for the theme README.
> SG-747 - Update header layout, README, theme info

- composer.json
- composer.lock
- patches/3092587-event-trigger-properties.patch
- patches/amplitude_config_options.patch
includes another patch to amplitude module to allow config options to be sent to amplitude init
> Sg 780 amplitude sbs

- composer.json
- composer.lock
- config/advagg.settings.yml
- config/core.entity_view_display.node.person.card_with_image_small.yml
- config/core.entity_view_display.paragraph.people.default.yml
- config/core.entity_view_mode.node.card_with_image_small.yml
- config/core.extension.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-1mayor.scss
- web/themes/custom/sfgovpl/templates/node/node--person--card-with-image-small.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--people.html.twig
* use smaller images for the people section as appropriate
> Sg 791 mobile performance

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/field/_featured-items.scss
- web/themes/custom/sfgovpl/src/sass/node/_node-transaction.scss
- web/themes/custom/sfgovpl/templates/node/node--transaction--full.html.twig
remove indents from need to know sections on transactions
sneak in a fix for dept featured items mobile
> Sg 820 need to know indent

- config/block.block.sfgovpl_page_title.yml
- config/core.entity_form_display.node.form_confirmation_page.default.yml
- config/core.entity_form_display.node.page.default.yml
- config/core.entity_view_display.node.form_confirmation_page.default.yml
- config/core.entity_view_display.node.form_confirmation_page.teaser.yml
- config/field.field.node.form_confirmation_page.body.yml
- config/field.field.node.form_confirmation_page.field_form_confirm_page_slug.yml
- config/field.storage.node.field_form_confirm_page_slug.yml
- config/language.content_settings.node.form_confirmation_page.yml
- config/node.type.form_confirmation_page.yml
- config/pathauto.pattern.form_confirmation_page.yml
- config/workflows.workflow.editorial.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/drupal.scss
- web/themes/custom/sfgovpl/src/sass/node/_node-form-confirmation.scss
- web/themes/custom/sfgovpl/templates/node/node--form-confirmation-page--full.html.twig
* form confirmation page configs (fields, pathauto)
* form confirmation page template
* form confirmation page scss
> Sg 797 fb confirmation page

- config/core.entity_view_display.node.form_confirmation_page.teaser.yml
- config/views.view.departments.yml
- config/views.view.services.yml
- web/themes/custom/sfgovpl/src/js/translate.js
config updates
small js update
> Views translation fixes

- README.md
updated circleci environment var to point to different location for sso certs
> added newline

- .circleci/scripts/ghost-inspector/run-gi-suite
output each test and status (pass/fail) from ghostinspector api
> Ci gi test output

- config/block.block.sfgovsearchblock.yml
- config/field.field.paragraph.block.field_block.yml
- config/views.view.events.yml
- config/views.view.services.yml
- web/themes/custom/sfgovpl/README.md
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/_mixins-fs.scss
- web/themes/custom/sfgovpl/src/sass/_mixins.scss
- web/themes/custom/sfgovpl/src/sass/_variables.scss
- web/themes/custom/sfgovpl/src/sass/block/_block-branding.scss
- web/themes/custom/sfgovpl/src/sass/components/_gtranslate.scss
- web/themes/custom/sfgovpl/src/sass/components/_header.scss
- web/themes/custom/sfgovpl/src/sass/components/_new-website.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-campaign.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-events.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-1mayor.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-2board.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-3elected.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-services.scss
- web/themes/custom/sfgovpl/templates/node/node--landing--full.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--campaign.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--people.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--section--default.html.twig
A refresh of the homepage.
Includes commits for numerous tickets, all under the epic https://sfgovdt.jira.com/browse/SG-955
> Homepage refresh

- config/views.view.events.yml
- web/themes/custom/sfgovpl/templates/views/views-view--events--block-1.html.twig
- web/themes/custom/sfgovpl/templates/views/views-view--news--block.html.twig
- Config for events view
- News & events view templates for buttons
> sg-973 - Make "see more" button show for news/events blocks

- config/core.entity_view_display.node.topic.card.yml
- config/field.field.node.event.field_image.yml
- config/image.style.350x200.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/node/_node-event-card.scss
- web/themes/custom/sfgovpl/templates/node/node--event--card.html.twig
- Adds a new image style
- Improves the position of the image
> sg-974 - Event card image size/position

- config/views.view.news.yml
update news topic page to use teaser
> sg-1006 update news topic page to use teaser

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/components/_gtranslate.scss
sg-1036 Fixed chinese language option that was cut off in language picker.
> sg-1036 Fixed chinese language option that was cut off in language picker

- config/views.view.news.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/_shame.scss
- web/themes/custom/sfgovpl/src/sass/components/_pager.scss
- web/themes/custom/sfgovpl/src/sass/drupal.scss
- web/themes/custom/sfgovpl/templates/navigation/pager.html.twig
> sg-636 - Views pagination styles

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/node/_node-news.scss
> sg-857 - Styles for full news nodes

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/node/_node-dept.scss
- web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig
Fixes SG-1003: Department homepage jump links are not pulling in all sections
> sg-1003 - Show department jump links

- config/core.entity_form_display.node.form_page.default.yml
- config/core.entity_form_display.paragraph.acuity_embed.default.yml
- config/core.entity_view_display.node.form_page.default.yml
- config/core.entity_view_display.node.form_page.teaser.yml
- config/core.entity_view_display.paragraph.acuity_embed.default.yml
- config/field.field.node.form_page.field_form_id.yml
- config/field.field.node.form_page.field_intro_text.yml
- config/field.field.paragraph.acuity_embed.field_form_id.yml
- config/paragraphs.paragraphs_type.acuity_embed.yml
- config/views.view.news.yml
- config/views.view.services.yml
- web/themes/custom/sfgovpl/templates/node/node--form-page--full.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--acuity-embed.html.twig
* adds Acuity form option under _Form page_ content type
* adds Intro field for _Form page_ content type (same field as Intro field used in _Step by Step_ content type)
* commits configuration updates for the production site that were not source controlled.
> Acuity form implementation 

- config/core.entity_form_display.paragraph.acuity_embed.default.yml
- config/core.entity_view_display.paragraph.acuity_embed.default.yml
- config/field.field.paragraph.acuity_embed.field_form_type.yml
- config/field.storage.paragraph.field_form_type.yml
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--acuity-embed.html.twig
* adds optional Appointment Type for Acuity Form.
> Acuity Appointment Type

- composer.json
- composer.lock
- config/core.extension.yml
- config/protected_pages.settings.yml
- config/user.role.anonymous.yml
- config/user.role.authenticated.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
* install Protected Pages module
* added some basic styling for protected pages password screen
> Protected Pages

- config/core.entity_form_display.paragraph.acuity_embed.default.yml
- config/core.entity_view_display.paragraph.acuity_embed.default.yml
- config/field.field.paragraph.acuity_embed.field_token_field_name.yml
- config/field.field.paragraph.acuity_embed.field_unauthorized_url.yml
- config/field.field.paragraph.acuity_embed.field_verification_url.yml
- config/field.storage.paragraph.field_token_field_name.yml
- config/field.storage.paragraph.field_unauthorized_url.yml
- config/field.storage.paragraph.field_verification_url.yml
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--acuity-embed.html.twig
* implements feature to authenticate with verification microservice to prevent unauthorized access to the Acuity scheduling form.
> Acuity authentication

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/_layout.scss
Implements a sticky footer globally using the [Solved by Flexbox method](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/). See screenshot for before (left) and after (right):
> [SG-1064] Implement a Sticky Footer.

- composer.lock
- config/core.entity_form_display.node.department.default.yml
- config/field.field.node.department.field_email.yml
- config/field.storage.node.field_email.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/components/_contact-items.scss
- web/themes/custom/sfgovpl/src/sass/node/_node-dept.scss
- web/themes/custom/sfgovpl/templates/field/department_full/field--node--field-address--department.html.twig
- web/themes/custom/sfgovpl/templates/field/department_full/field--node--field-email--department.html.twig
- web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig
- allow multiple email address for dept contact type
- refactor to use as much drupal template rendering as possible (ongoing refactor for dept content type to do it the "drupal" way)
- update drush to 8.3.2
> Sg 1061 dept email addrs

- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig
Proposing add trim to form data source URL to remove accidental white spaces in URL.
> Form data source url trim

- web/themes/custom/sfgovpl/includes/block.inc
- web/themes/custom/sfgovpl/templates/block/block--gtranslate-block.html.twig
> SG-1085 Language picker should reflect each option in the language it signifies.

- config/core.entity_form_display.node.meeting.default.yml
- config/core.entity_form_display.node.public_body.default.yml
- config/core.entity_form_display.paragraph.other_info_card.default.yml
- config/field.field.node.meeting.field_agenda.yml
- config/field.field.node.meeting.field_meeting_artifacts.yml
- config/field.field.node.meeting.field_regulations_accordions.yml
- config/field.field.node.public_body.field_board_members.yml
- config/field.field.node.public_body.field_callout.yml
- config/field.field.node.public_body.field_email.yml
- config/field.field.node.public_body.field_other_info.yml
- config/field.field.node.public_body.field_phone_numbers.yml
- config/field.field.node.public_body.field_public_body_meetings.yml
- config/field.field.paragraph.accordion_item.field_content.yml
- config/field.field.paragraph.other_info_card.field_resources.yml
This doesn't make any actual changes.  Current config doesn't ever report as imported due to sorting issues, which this resolves.
> Fix config export issues

- composer.json
- composer.lock
- patches/gtranslate_sfgov.patch
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/includes/block.inc
- web/themes/custom/sfgovpl/src/js/translate.js
- web/themes/custom/sfgovpl/src/sass/components/_gtranslate.scss
> sg 1141 -  GTranslate: Remove Translate <option>, Select Current Language

- config/image.style.campaign_logo.yml
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/node/_node-campaign.scss
This PR fixes:
- SG-1128
- SG-1129
- SG-1130
> sg-1128 - Adjust campaign logo width/height, reduce “padding” for logo.

- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--document--resource-collection.html.twig
> sg-1111 - Ensure field_file has content before printing.

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/templates/components/hero-banner-with-image.twig
- web/themes/custom/sfgovpl/templates/field/field--node--field-confirmation-sidebar--form-confirmation-page.html.twig
- web/themes/custom/sfgovpl/templates/node/node--form-confirmation-page--full.html.twig
Update form confirmation page CSS
> SG-1095: form confirmation page css

- web/themes/custom/sfgovpl/dist/css/critical.css
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/gulpfile.js
- web/themes/custom/sfgovpl/sfgovpl.info.yml
- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
- web/themes/custom/sfgovpl/src/sass/_base.scss
- web/themes/custom/sfgovpl/src/sass/components/_callout.scss
- web/themes/custom/sfgovpl/src/sass/drupal.scss
- web/themes/custom/sfgovpl/templates/components/callout.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--callout.html.twig
* fix and componentize callout
* remove sf-design-system as drupal library, import explicitly instead in sass
* add sass `includePaths` to make imports look a bit better
> Deploy issues

- web/themes/custom/sfgovpl/package-lock.json
- web/themes/custom/sfgovpl/package.json
These updates produced no changes to output.  ;)
> Update NPM dependencies.

- config/views.view.meetings.yml
> [SG-1207] Remove arrows from prev/next pager text.

- composer.json
- composer.lock
- config/core.extension.yml
...in hopes that this will help with some caching issues.
> [SG-1210] Install pantheon_advanced_page_cache module

- composer.lock
Branch name is incorrect, 8.9.1 is updated to 8.9.6
> Updates - D8 core 8.9.6

- .circleci/scripts/ghost-inspector/run-gi-suite
- .github/workflows/trigger-circleci-main.yml
- add content type header to curl request
- check for failures first for ghost inspector suite result
> gh action and ghost inspector suite results

- composer-manifest.yaml
- composer.lock
- config/core.entity_view_display.node.person.card.yml
- config/core.entity_view_display.node.person.card_with_image_small.yml
This gets both composer and Drupal config in line (no pending imports). I believe the manifest was missing from #628, because composer install likely wasn't run after updating the branch or after fixing conflicts.  Either way, this gets everything into a good state.
> Composer lock update + outstanding configuration

- config/sfgov_formio.settings.yml
See https://github.com/SFDigitalServices/formio-sfds/pull/109 for what's changed.
> Upgrade to formio-sfds@6.3.0

- config/sfgov_formio.settings.yml
~I'll open this for review once https://github.com/SFDigitalServices/formio-sfds/pull/125 is released.~
See [the 6.4.1 release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.4.1) for more info.
> Use formio-sfds@6.4.1

- web/themes/custom/sfgovpl/includes/html.inc
- web/themes/custom/sfgovpl/includes/page.inc
Fixes an error currently happening on http://sf.gov/ask-about-prep (while anonymous).
> Fix fatal error on unpublished campaigns.

- web/modules/custom/sfgov_departments/sfgov_departments.module
- web/modules/custom/sfgov_departments/src/Plugin/GroupContentEnabler/GroupMedia.php
- web/themes/custom/sfgovpl/templates/layout/page--403.html.twig
issues in pantheon `test` env resolved by @minnur in a different branch, cherry-picked here.  thanks @minnur 🧙 !
> Issue resource collection docs

- config/sfgov_formio.settings.yml
See the [release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v7.0.0) and https://github.com/SFDigitalServices/formio-sfds/pull/73 for more info.
> Upgrade formio-sfds to 7.0.0

- composer-manifest.yaml
- composer.json
- composer.lock
- config/core.extension.yml
- config/editor.editor.basic_html.yml
- config/editor.editor.full_html.yml
- config/editor.editor.sf_basic_html.yml
- config/editor.editor.sf_basic_html_news.yml
- config/editor.editor.sf_restricted_html.yml
- config/filter.format.basic_html.yml
- config/filter.format.full_html.yml
- config/filter.format.sf_basic_html.yml
- config/filter.format.sf_basic_html_news.yml
- config/filter.format.sf_restricted_html.yml
- config/image.style.linkit_result_thumbnail.yml
- config/linkit.linkit_profile.default.yml
- config/system.action.bulk_update_fields_on_linkit_profile.yml
- web/modules/custom/sfgov_moderation/sfgov_moderation.info.yml
SG-1193 Add and enable Linkit module to help translate internal links in WYSIWYG.
> SG-1193 Add and enable Linkit module to help translate internal links.

- config/pathauto.pattern.content.yml
- config/pathauto.pattern.departments.yml
- config/pathauto.pattern.events.yml
- config/pathauto.pattern.information.yml
- config/pathauto.pattern.meeting.yml
- config/pathauto.pattern.person.yml
- config/pathauto.pattern.public_body.yml
- config/pathauto.pattern.resource_collection.yml
- config/pathauto.pattern.standard.yml
- config/pathauto.pattern.step_by_step.yml
- config/pathauto.pattern.topics.yml
This PR is for https://sfgovdt.jira.com/secure/RapidBoard.jspa?rapidView=50&projectKey=SG&modal=detail&selectedIssue=SG-1069
> [SG-1069] Retain English URLs for translated content.

- web/modules/custom/sfgov_admin/css/dist/sfgov-admin.css
- web/modules/custom/sfgov_admin/css/src/components/_widget.entity_browser_entity_reference.scss
- web/modules/custom/sfgov_admin/css/src/sfgov-admin.scss
- web/modules/custom/sfgov_admin/sfgov_admin.module
Visual tweaks to image widgets.
> Sg 1293 image help text

- .circleci/config.yml
- composer.json
- composer.lock
- web/modules/custom/sfgov_admin/build/package-lock.json
- web/themes/custom/sfgovpl/package-lock.json
update packages to resolve security vulnerabilities
> Sg 1318 dependabot

- web/themes/custom/sfgovpl/templates/field/field--paragraph--field-title--thing-to-know.html.twig
Fixes [SG-1310]
[SG-1310]: https://sfgovdt.jira.com/browse/SG-1310
> [SG-1310] Fix closing tag

- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/sass/components/cards/_resource.scss
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--resources.html.twig
Fixes [SG-1296]
[SG-1296]: https://sfgovdt.jira.com/browse/SG-1296
> [SG-1296] Fix height and margin for resource card

- web/modules/custom/sfgov_event_subscriber/src/EventSubscriber/RedirectEventSubscriber.php
skip redirect logic if this is a preview url
> SG-1312 - do not redirect preview links

- web/themes/custom/sfgovpl/templates/node/node--topic--full-template-3.html.twig
- web/themes/custom/sfgovpl/templates/node/node--topic--full.html.twig
Fixes [SG-1286]
[SG-1286]: https://sfgovdt.jira.com/browse/SG-1286
> [SG-1286] Show spotlight first for topic template-3

- config/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_vaccine/config/install/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_vaccine/js/filter_sites.js
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.links.menu.yml
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.module
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.permissions.yml
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.routing.yml
- web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
- web/modules/custom/sfgov_vaccine/src/Form/FilterSitesForm.php
- web/modules/custom/sfgov_vaccine/src/Form/SettingsForm.php
- web/modules/custom/sfgov_vaccine/templates/vaccine-widget.html.twig
- web/themes/custom/sfgovpl/dist/css/critical.css
- web/themes/custom/sfgovpl/dist/css/drupal.css
- web/themes/custom/sfgovpl/src/js/exclude-from-gtranslate.js
- web/themes/custom/sfgovpl/src/sass/components/_banner.scss
- web/themes/custom/sfgovpl/src/sass/components/_vaccine-widget.scss
- web/themes/custom/sfgovpl/templates/components/atoms/vaccine-site-booking.twig
- web/themes/custom/sfgovpl/templates/misc/vaccine-widget.html.twig
**This PR requires a db update and a cache clear for deployment**
https://pr-843-sfgov.pantheonsite.io/vaccine-sites
[VAX-11], [VAX-12], [VAX-13], [VAX-16]
- Permissioned users can edit api url
- Filter behavior updates
- Animation on submit
- Show api url in HTML comments
- Fixed undefined notice in exclude-from-gtranslate.js
- Adds description text to the banner
[VAX-12]: https://sfgovdt.jira.com/browse/VAX-12
[VAX-13]: https://sfgovdt.jira.com/browse/VAX-13
[VAX-16]: https://sfgovdt.jira.com/browse/VAX-16
[VAX-11]: https://sfgovdt.jira.com/browse/VAX-11
> VAX Sprint 1

- web/modules/custom/sfgov_vaccine/js/filter_sites.js
https://pr-850-sfgov.pantheonsite.io/vaccine-sites
> [VAX-113] - Count all sites, not just ones that match filter.

- web/modules/custom/sfgov_vaccine/js/filter_sites.js
- web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
- web/modules/custom/sfgov_vaccine/src/Form/FilterSitesForm.php
- web/themes/custom/sfgovpl/templates/components/atoms/vaccine-site-booking.twig
- When available filter is checked, sites with apointment.available == false should be hidden.
- Restoring dropin functionality.
> Vax sprint 01-01

- pantheon.yml
- web/private/scripts/drush_config_import/drush_config_import.php
- web/private/scripts/new_relic/new_relic_deploy.php
add scripts to drush config import and create new relic deploy markers on pantheon hooks (deploy, sync_code)
> Pantheon hooks

- web/themes/custom/sfgovpl/includes/node.inc
- web/themes/custom/sfgovpl/includes/page.inc
- web/themes/custom/sfgovpl/sfgovpl.theme
- web/themes/custom/sfgovpl/templates/components/hero-banner-color.twig
- web/themes/custom/sfgovpl/templates/components/hero-banner-default.twig
- web/themes/custom/sfgovpl/templates/components/hero-banner-with-image.twig
- web/themes/custom/sfgovpl/templates/node/node--location--full.html.twig
> [SG-1331] Add no translate class to headings. (Re-up PR as patch)

- config/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_vaccine/js/filter_sites.js
- web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
- web/modules/custom/sfgov_vaccine/src/Form/FilterSitesForm.php
- adds target language to filters and changes ASL filter functionality.
> [VAX-147] Add target language to filter labels.

- config/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_vaccine/js/filter_sites.js
- web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--other.twig
- web/themes/custom/sfgovpl/templates/misc/vaccine-widget.html.twig
Removes the "Other Sites" function of the availability filter.
> [VAX-152] update availability filter

- config/field.field.node.form_confirmation_page.field_banner_image.yml
add config to translate file field on form confirmation page content type
> allow translation on file field for form confirmation content type

- config/core.entity_view_display.node.department.location_page.yml
- config/core.entity_view_display.node.department.search_index.yml
- config/language/es/views.view.watchdog.yml
- config/language/zh-hant/views.view.watchdog.yml
- config/sfgov_vaccine.settings.yml
- config/views.view.watchdog.yml
- web/modules/custom/sfgov_utilities/sfgov_utilities.module
- web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
- web/themes/custom/sfgovpl/includes/page.inc
- Added more filters to view. 
- Removed duplicate messages from view.
- Moved cron messages to their own tab.
- Did some code clean up.
- Adding logging for microservice connection failure.
> [Log cleanup]

- .circleci/scripts/tests/accessibility/accessibility-scan
specifc chromedriver version no longer necessary
> update axe core scan

- config/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_public_bodies/src/Form/MeetingListFiltersForm.php
- web/modules/custom/sfgov_vaccine/js/filter_sites.js
- web/modules/custom/sfgov_vaccine/js/location_autocomplete.js
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.libraries.yml
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.module
- web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
- web/modules/custom/sfgov_vaccine/src/Form/FilterSitesForm.php
- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
- web/themes/custom/sfgovpl/src/js/filters.js
- web/themes/custom/sfgovpl/src/sass/components/_vaccine-widget.scss
- web/themes/custom/sfgovpl/src/sass/view/_view-meetings-filters.scss
- web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-site.twig
- web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--filters.twig
- web/themes/custom/sfgovpl/templates/misc/vaccine-widget.html.twig
- Requires files to be pulled from live!
- Do not merge until okay'd by Nicole.
> [VAX-165] location filter

- web/themes/custom/sfgovpl/src/js/components.js
* grabs the show more text attribute from the appropriate element
> Sg 1362 toggle

- config/sfgov_vaccine.settings.yml
- web/modules/custom/sfgov_event_subscriber/sfgov_event_subscriber.services.yml
- web/modules/custom/sfgov_event_subscriber/src/EventSubscriber/RedirectEventSubscriber.php
> main merge pr 

- composer-manifest.yaml
- composer.json
- composer.lock
> small fixes for dependency updates

- .gitignore
- README.md
- composer-manifest.yaml
- composer.json
- composer.lock
- config/config_split.config_split.sfgov_utilities.yml
- config/system.performance.yml
- config/tmgmt.translator.contentapi.yml
https://www.drupal.org/sa-core-2021-003
> update drupal core to 8.9.16

- composer-manifest.yaml
- composer.lock
* Updates chaos tools to 3.7.0 to address security vulnerability: https://www.drupal.org/sa-contrib-2021-015
* also updates other modules
> update ctools to 3.7.0 + other module updates

- config/sfgov_formio.settings.yml
See the release notes for both [9.0.0](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.0.0) and [9.1.0](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.1.0) for more info.
> Bump formio-sfds to 9.1.0

- web/themes/custom/sfgovpl/src/sass/_base.scss
- web/themes/custom/sfgovpl/templates/node/node--public-body--full.html.twig
* fix up links, will reopen SG-1434
* use t filter on headings
> Release fixes v08022021 (#969)

- web/modules/custom/sfgov_admin/sfgov_admin.module
> [SG-1433] Update power bi default values for resource collection

- web/themes/custom/sfgovpl/src/sass/node/_node-resource-collection.scss
> [SG-1442] Fix left and right padding for resource collection intro text

- web/themes/custom/sfgovpl/src/sass/node/_node-report.scss
> [SG-1451] Fix styling issues with report nodes

- config/core.entity_form_display.node.report.default.yml
- config/core.entity_view_display.node.report.default.yml
- config/field.field.node.report.field_print_version.yml
- config/field.storage.node.field_print_version.yml
- web/themes/custom/sfgovpl/includes/node.inc
- web/themes/custom/sfgovpl/templates/node/node--report--full.html.twig
> [SG-1452] Add print version field to report content type

- web/modules/custom/sfgov_campaigns/sfgov_campaigns.module
URL addresses and email addresses break the tiles, so check this value when a user adds to the form, and throw a form error if found.
> [SG-1408] Add check for resource description field

- composer-manifest.yaml
- composer.json
- composer.lock
There were 2 missing entries in `composer.json` that have been added back in.
> SG-1476 Remove group module & patches

- config/filter.format.sf_full_html_with_toc.yml
- web/modules/custom/sfgov_doc_html/src/Plugin/Filter/ResponsiveTableFilter.php
- web/themes/custom/sfgovpl/src/sass/node/_node-report.scss
> [SG-1444] Improve responsive behavior for tables

- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-powerbi-embed.scss
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--powerbi-embed.html.twig
Fixes [SG-1446]
[SG-1446]: https://sfgovdt.jira.com/browse/SG-1446
> [SG-1446] Display issues with powerBI embeds

- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--call-to-action.html.twig
> [SG-1420] Call to action button on Events doesn't work if you use a link search

- web/modules/custom/sfgov_admin/sfgov_admin.libraries.yml
- web/modules/custom/sfgov_admin/sfgov_admin.module
- web/modules/custom/sfgov_admin/tmp/sg-1498/script.js
- web/modules/custom/sfgov_admin/tmp/sg-1498/style.css
This is a temporary solution to solve urgent issue.
> [SG-1498] Temporary solution to reduce length of the translation revision logs.

- composer.json
This reverts commit 4d8732b78e4f31da413a2a30cbf989723b433662.
> Revert "patch lionbridge swagger config to use staging endpoint (#1068)"

- config/image.style.profile.yml
|before|after|
|-------|-------|
|<img width="334" alt="Screen Shot 2021-11-02 at 12 21 03 AM" src="https://user-images.githubusercontent.com/19291154/139802980-0ea5e62b-966e-489a-8309-cf4f015b0183.png">|<img width="332" alt="Screen Shot 2021-11-02 at 12 21 41 AM" src="https://user-images.githubusercontent.com/19291154/139803045-f04eaa1b-6da7-4052-a2c8-59a16a469967.png">
> SG-1556 - reposition profile image style

- web/themes/custom/sfgovpl/package-lock.json
- web/themes/custom/sfgovpl/package.json
- web/themes/custom/sfgovpl/src/sass/node/_node-person.scss
fixes some view issues on the small screen profile:
- Several text styles should use the equivalent mobile text style. 
- Name should be Display 1 mobile
- The City Employee job title should be Big description mobile
- Additional City roles should be Title 2 mobile
- Contact  should be Title 1 mobile
- On External profiles, the job title should be Title 3 mobile
- The spotlight image has some display issues
- Featured items are getting more spacing than the spotlight. Should just be 20px left and right.
> Sg 1564 mobile profile

- config/sfgov_formio.settings.yml
See the [release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.2.2) for more info.
> Upgrade formio-sfds to 9.2.2

- web/modules/custom/sfgov_event_subscriber/src/EventSubscriber/RedirectEventSubscriber.php
Update Drupal\file\Entity\File::url() with Drupal\file\Entity\File::createFileUrl()
> D9 compatibility for file url method

- web/themes/custom/sfgovpl/package.json
- web/themes/custom/sfgovpl/sfgovpl.libraries.yml
Bundle the necessary design system js with our drupal theme js
> bundle sfds js with theme js

- .github/workflows/amplitude.yml
Let's try this again... for SG-1550.
> Fix Amplitude event triggers from GitHub Actions

- composer-manifest.yaml
- composer.lock
Updates core to 9.3.3: https://www.drupal.org/project/drupal/releases/9.3.3
Addresses this security vulnerability: https://www.drupal.org/sa-core-2022-001.  Relevant parts as follows:
> **Vulnerability**: 
Cross Site Scripting
>
>**Description**: 
jQuery UI is a third-party library used by Drupal. This library was previously thought to be end-of-life.
>
> Late in 2021, jQuery UI announced that they would be continuing development, and released a jQuery UI 1.13.0 version. As part of this 1.13.0 update, they disclosed the following security issue that may affect Drupal 9 and 7:
>
> - CVE-2021-41183: [XSS in the of option of the .position() util](https://github.com/jquery/jquery-ui/security/advisories/GHSA-j7qv-pgf6-hvh4)
>
>It is possible that this vulnerability is exploitable with some …
> update to core 9.3.3

- composer-manifest.yaml
- composer.json
- composer.lock
Updates lionbridge drupal module to 2.12, which fixes the auto-import feature
> update lionbridge to 2.12

- composer.json
- composer.lock
- config/core.base_field_override.node.form_page.path.yml
- config/core.base_field_override.paragraph.form_io.created.yml
- config/core.base_field_override.paragraph.form_io.status.yml
- config/core.entity_form_display.node.form_page.default.yml
- config/core.entity_view_display.node.form_page.default.yml
- config/core.entity_view_display.node.form_page.teaser.yml
- config/core.extension.yml
- config/field.field.node.form_page.field_formio_json_content.yml
- config/field.field.paragraph.form_io.field_formio_confirmation_url.yml
- config/field.field.paragraph.form_io.field_formio_data_source.yml
- config/field.field.paragraph.form_io.field_formio_render_options.yml
- config/field.storage.node.field_formio_json_content.yml
- config/sfgov_formio.settings.yml
- patches/lionbridge-host-update.patch
- web/modules/custom/sfgov_formio/README.md
- web/modules/custom/sfgov_formio/sfgov_formio.module
- web/modules/custom/sfgov_formio/src/Form/Settings.php
- web/modules/custom/sfgov_formio/src/Plugin/Field/FieldType/Formiourl.php
- web/modules/custom/sfgov_formio/src/Plugin/Field/FormioFieldProcessor.php
- web/themes/custom/sfgovpl/includes/paragraph.inc
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig
Note, this is both SG-1532 and SG-1534 (Getting the frontend to work)
> SG-1532  form translation source plugin

- config/sfgov_vaccine.settings.yml
From "Only show sites with confirmed availability" to "Open appointment or drop-in"
> Update vaccine-sites form_strings.available

- composer-manifest.yaml
- composer.json
- composer.lock
- config/core.extension.yml
- config/csp.settings.yml
https://www.drupal.org/project/csp
To address:
from: https://snyk.io/test/website-scanner/?test=220120_BiDcPS_57ae631df094d518528f5efb69f968ab
> Install and enable content security policy module

- composer-manifest.yaml
- composer.json
- composer.lock
- update lionbridge to 2.13
- apply core patch for saving views
> Lionbridge 2.13

- .lando.yml
- README.md
- composer-manifest.yaml
- composer.json
- composer.lock
- phpcs.xml
@aekong @shawnbot. Closing the original PR, this one includes everything we discussed and has a cleaner commit history + ticket number reference
> 1656: setup lando phpcs and phpcbf

- web/themes/custom/sfgovpl/src/sass/node/_node-dept.scss
- web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig
https://sfgovdt.jira.com/browse/SG-1604
> Fixing top spacing on Staff Section

- config/sfgov_formio.settings.yml
See the [release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.2.4) for more info.
> Bump formio-sfds to 9.2.4

- web/themes/custom/sfgovpl/includes/node.inc
- web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig
expose language to node templates, use for profile entity reference translation check
> profile - translate department/public body entity reference if translation exists

- config/sfgov_formio.settings.yml
See the [release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.2.5) for more info.
> Bump formio-sfds@9.2.5

- config/core.entity_form_display.node.department.default.yml
- config/editor.editor.sf_basic_html_with_restricted_headings.yml
- config/field.field.node.department.field_alert_text.yml
- config/field.field.node.form_confirmation_page.body.yml
- config/field.field.node.location.field_intro_text.yml
- config/field.field.paragraph.accordion_item_simple.field_text.yml
- config/field.field.paragraph.additional_info.field_additional_info_text.yml
- config/field.field.paragraph.agenda_item.field_text_agenda_item.yml
- config/field.field.paragraph.callout.field_text.yml
- config/field.field.paragraph.campaign_spotlight.field_description.yml
- config/field.field.paragraph.cost.field_text.yml
- config/field.field.paragraph.fact.field_description.yml
- config/field.field.paragraph.help.field_text.yml
- config/field.field.paragraph.special_case.field_text.yml
- config/field.field.paragraph.spotlight.field_description.yml
- config/field.field.paragraph.thing_to_know.field_text.yml
- config/field.field.paragraph.video.field_description.yml
- config/field.field.paragraph.video.field_text.yml
- config/field.field.paragraph.video_external.field_description.yml
- config/filter.format.sf_basic_html_with_restricted_headings.yml
- config/user.role.authenticated.yml
- config/user.role.digital_services.yml
- config/user.role.publisher.yml
- config/user.role.writer.yml
- web/modules/custom/sfgov_admin/sfgov_admin.module
Reset certain long, formatted text fields to different text formats, based on instructions from https://airtable.com/shrIVVZY2qtfySKaf/tblKqPZ4wFxBOPDC3
Changed the character count on department about description field to 450 from 2500, based on notes from airtable link.
> [SG-1713] - Update current text format to the new desired format.

- web/themes/custom/sfgovpl/templates/components/phone.twig
- web/themes/custom/sfgovpl/templates/field/field--paragraph--field-title--thing-to-know.html.twig
Changed phone twig component to an h5 tag. 
Changed title field for things to know paragraphs to an h2 tag.
Clearing caches is all thats needed to trigger new tags.
> [SG-1701] - Fix reading order accessibility issues on transactions

- config/views.view.news.yml
fix already in production (view config).  this pr preserves those changes on production deploy
> SG-1690 - fix news page coming up empty

- composer-manifest.yaml
- composer.json
- composer.lock
plus a bunch of other module updates
> core update to 9.3.14, lionbridge update to 2.16

- config/sfgov_formio.settings.yml
[This release](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v9.2.7) brings a bunch of front end bug fixes.
> Upgrade formio-sfds to 9.2.7

- web/themes/custom/sfgovpl/includes/page.inc
- web/themes/custom/sfgovpl/templates/layout/page--node--campaign.html.twig
* render node title, screen reader only if logo exists
> SG-1774 - Campaign accessibility

- web/themes/custom/sfgovpl/src/sass/components/_details.scss
- web/themes/custom/sfgovpl/src/sass/components/cards/_resource.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-resources.scss
- web/themes/custom/sfgovpl/templates/field/resources/field--node--field-resources.html.twig
#SG-1764
Setup the resource and service sections on department pages, to look the same
when in accordion states on mobile and small screens.
> [SG-1764] -- style match resource section and service sections

- web/themes/custom/sfgovpl/src/sass/_mixins.scss
SG-1765 - broke the border radius on accordions
> v08102022 release fixes

- config/editor.editor.basic_html.yml
- config/editor.editor.full_html.yml
- config/editor.editor.sf_basic_html.yml
- config/editor.editor.sf_basic_html_news.yml
- config/editor.editor.sf_basic_html_with_restricted_headings.yml
- config/editor.editor.sf_full_html_with_toc.yml
- config/editor.editor.sf_restricted_html.yml
- config/editor.editor.sf_restricted_inline_html.yml
- config/views.view.media.yml
- config/views.view.search.yml
SG-1234
Add the ability to filter media by author on the media content view
> Media author filter

- config/field.field.node.form_confirmation_page.body.yml
SG-1234 
Remove body summary field on form confirmation page content type
> remove body summary field

- config/views.view.media.yml
SG-1376
* Update the media author filter label to "Authored by"
> update media author filter label

- web/themes/custom/sfgovpl/src/sass/node/_node-transaction.scss
SG-1826
* update link color for cost description on transactions
> SG-1826 - Link color is inaccessible in Cost Description section

- config/core.entity_form_display.node.person.default.yml
- config/core.entity_view_display.node.person.card.yml
- config/core.entity_view_display.node.person.card_with_image_small.yml
- config/core.entity_view_display.node.person.default.yml
- config/core.entity_view_display.node.person.person_section_display.yml
- config/core.entity_view_display.node.person.teaser.yml
- config/field.field.node.person.field_pronouns.yml
- config/field.storage.node.field_pronouns.yml
- web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig
SG-1768
* Add a new field to profile content type - pronouns
* Update profile template to include pronouns display
> SG-1768 profile pronouns

- pantheon.yml
- web/modules/custom/sfgov_profiles/sfgov_profiles.deploy.php
- web/modules/custom/sfgov_profiles/src/migration-scripts/migrate-bio.php
- web/modules/custom/sfgov_profiles/src/migration-scripts/resave-public-body.php
- web/private/scripts/drush-deploy/drush-deploy-hook.php
- web/private/scripts/drush_config_import/drush_config_import.php
SG-1234
execute deploy hooks when deployed, add backup scripts that can be executed via drush scr if deploy:hook doesn't run
> deploy hook execution

- web/themes/custom/sfgovpl/templates/components/person-card.twig
SG-1234
* fix various release issues
> v08312022 release issues

- config/core.entity_view_display.node.campaign.teaser.yml
- config/core.entity_view_display.node.resource_collection.default.yml
- config/field.field.node.information_page.field_related_content.yml
- config/field.field.node.transaction.field_related_content.yml
- web/themes/custom/sfgovpl/includes/field.inc
Add campaigns and resource collections as options to related content sections on transaction and information pages.
> #SG-1632 -- Add campaigns and resource collections to related content sections

- package-lock.json
- web/modules/custom/sfgov_utilities/js/sfgov_utilities_services.js
- web/themes/custom/sfgovpl/package.json
- web/themes/custom/sfgovpl/scripts/copy-design-system-files.sh
- web/themes/custom/sfgovpl/src/sass/utilities.css
- web/themes/custom/sfgovpl/templates/components/featured-item.twig
SG-1819 - update design system to 2.5 to fix duplicate icons
> SG-1819 duplicate icons

- config/views.view.meetings.yml
- web/modules/custom/sfgov_dates/sfgov_dates.module
- web/modules/custom/sfgov_dates/src/Plugin/Field/FieldFormatter/SfgovDateFormatterBase.php
- web/modules/custom/sfgov_dates/src/Plugin/Field/FieldWidget/SfgovSmartdateWidget.php
Reverts SFDigitalServices/sfgov#1393
> Revert "1820: adjust meeting timing display"

- composer-manifest.yaml
- composer.json
- composer.lock
- web/modules/custom/sfgov_locations/src/AddressField.php
- web/modules/custom/sfgov_locations/src/AddressFormat.php
- web/modules/custom/sfgov_locations/src/Repository/AddressFormatRepository.php
* core update to 9.4.6
* update lionbridge to 2.17
> update core to 9.4.6, update lionbridge to 2.17, other package updates

- web/themes/custom/sfgovpl/src/sass/node/_node-resource-collection.scss
Set size for h2 from 40/47 to 44/52 and for h3's from 40/47 to 32/36
> SG-1860 -- Style fix to resource collection h2/h3's in intro text.

- config/views.view.news.yml
SG-1866 -- See more news link not showing on some department news listings
Reordering of view displays fixed this.
> SG-1866 -- See more news link not showing on some department news listings

- composer-manifest.yaml
- composer.json
- composer.lock
- patches/media_entity_file_replace--update-labels.patch
SG-123
* drupal core 9.4.8
* lionbridge 2.19
* repatch `media_entity_file_replace` post update for clearer replace help text
> update core to 9.4.8, lionbridge to 2.19

- web/themes/custom/sfgovpl/includes/views.inc
Fix Department nodes "see more news" button, which is displaying when it should not display
> SG-1877 -- Fix Department nodes "see more news" button, which is displaying when it should not display

- web/modules/custom/sfgov_qless/src/Services/QLess.php
Added:
(2395) Permit Processing: No plans / Trade
(2718) Office of Small Business (OSB Permit Center)
(2586) Public Health: Plan review
> SG-1873 -- Add 3 more Qless queues to wait times.

- composer.json
> SG-1869 - feat: patch core to allow unpublished entities

- web/themes/custom/sfgovpl/templates/layout/page--node--campaign.html.twig
I've added the notranslate class to the campaign title to prevent machine/google translation
> SG-1833 -- Make campaign title human translatable.

- config/search_api.index.content.yml
- config/views.view.zz_sf_gov_reports.yml
SG-1854 department and public body migration needs a lot of reports for verifying data is being moved around correctly.  Creating a reports view for this effort and future efforts.
> add reports view

- web/modules/custom/sfgov_admin/.eslintignore
- web/modules/custom/sfgov_admin/js/sfgov-admin.js
- web/modules/custom/sfgov_admin/js/sfgov-maxlength.js
- web/modules/custom/sfgov_admin/tmp/sg-1498/script.js
No Task ID
This is to help it pass js linting tests
> CLEANUP -- Js linting cleanup of custom sfgov-maxlength.js code

- web/modules/custom/sfgov_translation/sfgov_translation.install
SG-1880
fixes error `Unknown column 'translation_outdated`
> SG-1880 - add install file for sfgov_translation

- web/themes/custom/sfgovpl/templates/node/node--event--card.html.twig
- web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig
* add alt text for profile map image
* add alt text for event card image
> SG-1919 and SG-1920 alt text for images

- .github/workflows/checks.yml
- package-lock.json
- web/modules/custom/sfgov_vaccine/js/location_autocomplete.js
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.libraries.yml
- web/modules/custom/sfgov_vaccine/sfgov_vaccine.module
- web/themes/custom/sfgovpl/templates/misc/vaccine-widget.html.twig
SG-1940
* remove `p-0` utility class on filter container
* remove async loading on js scripts
* the google maps api calback parameter was reporting that `locationAutocomplete` was not found
> SG-1940 - vaccine sites filter

- config/core.entity_form_display.node.department.default.yml
- config/field.field.node.department.field_description.yml
- config/views.view.group_members.yml
SG-1938
* require description field on agency content type and soft limit 140 characters
> SG-1938  - require agency description

- config/sfgov_formio.settings.yml
This resolves an issue with `<sfgov-icon>` elements in form HTML preventing forms from rendering. cc @josh-chou
> Upgrade formiojs to 4.14.8

- composer-manifest.yaml
- composer.json
- composer.lock
- config/automated_cron.settings.yml
- config/core.extension.yml
* install and enable the xtm tmgmt plugin
> install and enable tmgmt xtm plugin

- composer-manifest.yaml
- composer.json
- composer.lock
- config/user.role.publisher.yml
- config/user.role.writer.yml
SG-1234
* prevent editors from being able to create/edit/delete public body content and their revisions
* composer update contrib modules
> Lock public body permissions

- composer.json
- pantheon.yml
SG-1943
Apply patch for views_data_export issue: [3173296](https://www.drupal.org/project/views_data_export/issues/3173296)
> SG-1943 - apply patch for views data export issue 3173296

- config/views.view.events.yml
SG-1930 - always display the show more button for topic event block
> SG-1930 - show more button for topic events

- config/field.field.paragraph.agency_section.field_agencies.yml
- config/field.field.paragraph.agency_section.field_section_title_list.yml
- web/modules/custom/sfgov_departments/sfgov_departments.module
- web/themes/custom/sfgovpl/includes/node.inc
- web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig
SG-1959
* Make the agency section title required if agency section added
* Check that indices exist on custom validation
> SG-1959 - fix wsod for empty agency section, make section title required

- web/themes/custom/sfgovpl/includes/node.inc
SG-1947
fix wsod if there are no data story subsections on reports to iterate through
> SG-1947 - data page breaks

- web/modules/custom/sfgov_departments/sfgov_departments.module
SG-1956
* fixes a php error regarding incorrect offset
> SG-1956 - check for existing offset

- web/themes/custom/sfgovpl/templates/components/hero-banner-color.twig
SG-1963
* use raw value for header title
> SG-1963 - use raw value for header title in banner

- composer.json
- composer.lock
SG-1961
* datalayer custom dimensions are getting lost
> SG-1961 - patch rc version of datalayer for multivalue

- composer-manifest.yaml
- composer.lock
* includes core update to 9.5.4
> update composer dependencies

- web/themes/custom/sfgovpl/src/sass/components/_banner.scss
- web/themes/custom/sfgovpl/src/sass/forms/_form-fields.scss
- web/themes/custom/sfgovpl/src/sass/page/_page-404.scss
- web/themes/custom/sfgovpl/templates/block/block--404pagenotfound.html.twig
- web/themes/custom/sfgovpl/templates/field/field--paragraph--field-link--campaign.html.twig
- web/themes/custom/sfgovpl/templates/node/node--campaign--full.html.twig
- web/themes/custom/sfgovpl/templates/node/node--location--full.html.twig
- web/themes/custom/sfgovpl/templates/node/node--public-body--full.html.twig
SG-1922
Homepage spotlight button, "Part of" department snippet on meetings, Page not found content links adjusted to have better color contrast on the indicator
> [SG-1922] -- Color Contrast Issues with keyboard focus indicators

- web/themes/custom/sfgovpl/includes/field.inc
Removed string of text 'BACON' used for testing from output
> Removed string of text used for testing from output

- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--cost--step-by-step-cost.html.twig
SG-1975
* use the value from the paragraph entity for the minimum cost
> SG-1975 - minimum cost fix

- config/views.view.content.yml
> feat: translation content view published any

- web/themes/custom/sfgovpl/src/sass/node/_node-person.scss
- web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig
[SG-2004]
Social media and contact information is not showing on mobile profile pages
[SG-2004]: https://sfgovdt.jira.com/browse/SG-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SG-2004] -- Social media and contact information is not showing on mobile profile pages

- config/pathauto.pattern.department_table.yml
[SG-2005]
Add new pathauto config for department table content type. Set to "department-table/[node:source:title]”
[SG-2005]: https://sfgovdt.jira.com/browse/SG-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SG-2005] -- Add new pathauto config for department table content type.

- config/user.role.publisher.yml
- config/user.role.writer.yml
[SG-2006]
Remove permissions related to department tables from writers and publishers. Only allow digital services and admin roles those permissions.
[SG-2006]: https://sfgovdt.jira.com/browse/SG-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SG-2006] -- Remove permissions related to department tables from writers and publishers.

- config/views.view.news.yml
- web/themes/custom/sfgovpl/src/sass/components/_news-front.scss
- web/themes/custom/sfgovpl/templates/components/molecules/news-cards.twig
- web/themes/custom/sfgovpl/templates/components/news-front.twig
- web/themes/custom/sfgovpl/templates/views/views-view-unformatted--news--block.html.twig
SG-2016
* remove twitter feed from front page
* tile news items
* increase news item count
> SG-2016 - fix: remove twitter feed, tile and increase news tiles

- config/image.style.profile_small.yml
- web/themes/custom/sfgovpl/templates/node/node--person--card-with-image-small.html.twig
SG-2031. Added a profile small image style for use with the profile small view mode.
> SG-2031 -  smaller image size for small profile display

- web/themes/custom/sfgovpl/src/sass/components/_person-card.scss
- web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-1mayor.scss
- web/themes/custom/sfgovpl/templates/components/person-card.twig
SG-2034 Adding lazy load to person cards so person profile small images are more performant on the home page.
> SG-2034 - lazy load person card images

- web/themes/custom/sfgovpl/src/sass/node/_node-resource-collection.scss
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--data-story-reference-section.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--document-section.html.twig
- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--resource-section.html.twig
> feat: clean up mb for different sections.

- composer-manifest.yaml
- composer.json
- composer.lock
- config/core.extension.yml
- config/honeypot.settings.yml
- config/webform.webform.was_this_page_helpful_.yml
SG-2056 webform spam prevention with honeypot
> feat: adding honeypot spam prevention

- config/views.view.news.yml
SG-2046. Fixing news view duplicates.
> feat: fix news view duplicates

- config/field.field.node.event.field_smart_date.yml
- config/views.view.user_admin_people.yml
- web/themes/custom/sfgovpl/templates/node/node--location--full.html.twig
* SG-2064 - fix the color on location page alert
* make Event date field required
> SG-2064 - location alert

- config/field.field.node.information_page.field_information_section.yml
fix for missing callouts on info pages
> feat: adding back in callout on info pages

- config/amplitude.settings.yml
- config/core.extension.yml
- config/sfgov_amplitude.tokens.settings.yml
- config/user.role.digital_services.yml
configuration export from production.  follow-up for removing amplitude
> production configuration export

- config/views.view.content.yml
- config/views.view.user_admin_people.yml
config exports some things already on live
- updates content view data export to include link to content field
- add report for all active users
> update content download csv

- composer-manifest.yaml
- composer.lock
- config/views.view.zz_sf_gov_reports.yml
- pantheon.yml
SG-2075
Resolve merge conflicts with `develop`
> merge develop

- composer-manifest.yaml
- composer.json
- composer.lock
- config/views.view.events.yml
- web/themes/custom/sfgovpl/templates/views/views-view--events--block-1.html.twig
- contrib updates
- patches for core and smart_date
> SG-2095 - missing more button for agency events, contrib updates

- web/themes/custom/sfgovpl/templates/paragraphs/paragraph--resource-node.html.twig
follow-up to SG-2119.  render, then striptags
> SG-2119 - strip tags on resource tile descriptions

- composer-manifest.yaml
- composer.lock
SG-1234
* composer update
* drupal core 10.2.4
> chore: update composer dependencies (includes core update 10.2.4)

- config/core.entity_form_display.node.report.default.yml
- config/core.entity_form_display.paragraph.document.default.yml
- config/core.entity_form_display.paragraph.other_info_document.default.yml
- config/core.entity_form_display.paragraph.resource_entity.default.yml
- config/google_tag.container.sfgov.yml
- config/views.view.eck_resources.yml
SG-2120
add eck resource admin view with search filter on title and link to edit
> SG-2120 - follow-up, add eck resource view and menu item

- composer-manifest.yaml
- composer.json
- composer.lock
SG-2135
Updates google tag to ^2.0
> SG-2135 - update google_tag to ^2.0

- config/field.field.node.about.field_parent_department.yml
- config/field.field.node.page.field_dept.yml
- config/field.field.node.person.field_city_department.yml
- config/field.field.node.report.field_departments.yml
Adds field_departments to the datalayer on report nodes
> SG-2140 - feat: add report department to datalayer

- composer-manifest.yaml
- composer.json
- composer.lock
- drupal core 10.2.6
- other contrib module updates
> chore: update drupal core to 10.2.6, other module updates

- config/field.field.location.event_address.field_address.yml
SG-2166
Reopen this pr post prod config export
> feat: make zip on event locations required

- config/field.field.node.department.field_req_public_records_phone.yml
- config/field.field.node.person.field_primary_phone_number.yml
SG-2165
Reopen this pr post config export
> feat: update tel fields to have validation

- web/modules/custom/sfgov_api/src/Plugin/SfgApi/Eck/Resource.php
- web/modules/custom/sfgov_api/src/Plugin/SfgApi/Node/Campaign.php
Necessary changes for the data migration:
* Add fields for Campaign, ECK Resource
* Rename fields for output
https://sfgovdt.jira.com/browse/CMS-349
> Feature/cms 349/migrate campaign

- web/sites/default/services.pantheon.preproduction.yml
> chore: turn off debug

- web/modules/custom/sfgov_api/src/Plugin/SfgApi/Node/ResourceCollection.php
- web/modules/custom/sfgov_api/src/Plugin/SfgApi/Paragraph/DataStoryReferenceSection.php
- web/modules/custom/sfgov_api/src/Plugin/SfgApi/Paragraph/DataStoryReferenceSubsection.php
Added the necessary "plug-ins" so that the API can serialize it out. And, as a bonus, add back in commented out fields!
https://sfgovdt.jira.com/browse/CMS-499
> bugfix(CMS-499): Create module to serialize out data story references

- config/field.field.node.resource_collection.field_content.yml
- config/system.site.yml
- config/user.role.digital_services.yml
- config/user.role.publisher.yml
- config/user.role.writer.yml
- config/views.view.content.yml
- config/views.view.derek_page_level_redirects.yml
- config/views.view.redirect.yml
- config/views.view.zz_sf_gov_reports.yml
configuration export from production 11/20/2024
> prod config export 
