SFDigitalServices/sfgov

composer.lock

Pantheon Drops-8 is a couple of minor versions behind. 
Notes:
- There is no related configuration.
- No database updates are required.

SG-88: Update Drupal core to 8.5.3.

---

config/block.block.search_page_block_sfgov.yml

I added the search form on the search page but since it's not in config, it will be removed as soon as the next `drush cim` happens without this config file.

[SG-192] Adds the search form to the search page on the sfgov theme.

---

config/core.entity_form_display.node.transaction.default.yml
config/core.entity_form_display.paragraph.section.default.yml
tests/features/bootstrap/FeatureContext.php
tests/features/content.feature
web/modules/custom/sfgov_admin/js/dist/sfgov-admin.js
web/modules/custom/sfgov_admin/js/src/sfgov-admin.js
web/modules/custom/sfgov_admin/src/Plugin/Field/FieldWidget/SfgovParagraphsWidget.php
web/modules/custom/sfgov_admin/tests/src/Unit/Plugin/Field/FieldWidget/SfgovParagraphsWidgetTest.php

For landing page sections, the button to add content to sections will use the new and improved widget. The initial add entry will appear as "Add" and subsequent entries will appear by their paragraph type name.

[SG-183] Add-drop widget

---

composer.json
composer.lock

My understanding is that we were continuously retagging `sfgov-pattern-lab` as `0.1` every time we updated master. This just points to the `master` branch.
I think this is preferable as:
* it simplifies the workflow during this initial rapid development push
* git tags are meant to be immutable
Eventually we will likely want to start tagging official releases of the pattern library using semantic versioning or similar, especially as more projects begin to depend on it, but this seems sensible for the time being.

Pin sfgov-pattern-lab to the master branch

---

web/modules/custom/sfgov_utilities/sfgov_utilities.module

use the redirect instead of directly using external url.  a test for this exists at /tests/features/sfgov.feature

sg-369 bring back event subscriber for transaction redirects

---

web/modules/custom/sfgov_search/js/sfgov_search.js
web/themes/custom/sfgovpl/src/js/navigation.js
web/themes/custom/sfgovpl/src/sass/_layout.scss
web/themes/custom/sfgovpl/src/sass/block/_block-search-small.scss
web/themes/custom/sfgovpl/src/sass/components/_header.scss

Resolves: 
1 - keyword should be bolded in autocomplete results
2 - small gap between the "X" and the colored banner.
3 - The small gray X inside the search bar is not vertically aligned.
4 - Once I opened the "Menu", then pressed on the "Search" icon things start breaking. The red highlighted "X" should remain as "Menu" on the header.

571 mobile search b

---

config/field.field.paragraph.link.field_link.yml
web/modules/custom/sfgov_utilities/sfgov_utilities.module

Use help text from “Link” field under uri input field, replacing “Start typing the title of a piece of content to select it...” default description

sg-565 - use link help text for uri if available

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/img/search-dark-blue.svg
web/themes/custom/sfgovpl/src/sass/block/_block-search.scss

High-level note -
Some (butt not all) buttons were styled on the wrapper instead of input. I'm trying to make them all consistently styled on the input and that will help with hit areas matching the visual expectation and make future theme updates to all search easier.

SG-678 Hit area and hover states for search!

---

config/core.entity_view_display.node.form_page.teaser.yml
config/mailsystem.settings.yml

branch name is inaccurate.  all this does is at the moment is solve the problem of not being able to update a user's status from `blocked` to `active`.  Ticket for context: https://sfgovdt.jira.com/browse/SG-732
removing a module and having config export and composer sync'd up is a multistep process apparently: https://drupal.stackexchange.com/questions/271202/disabling-module-with-config-sync-and-removing-with-composer

config export to update mailsystem

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/components/_sidebar-card.scss
web/themes/custom/sfgovpl/src/sass/drupal.scss
web/themes/custom/sfgovpl/src/sass/node/_node-transaction-help.scss
web/themes/custom/sfgovpl/src/sass/node/_node-transaction-related-services.scss
web/themes/custom/sfgovpl/src/sass/node/_node-transaction.scss
web/themes/custom/sfgovpl/templates/components/atoms/sidebar-card.twig
web/themes/custom/sfgovpl/templates/field/field--node--field-help--transaction.html.twig
web/themes/custom/sfgovpl/templates/field/field--node--field-transactions--transaction.html.twig
web/themes/custom/sfgovpl/templates/node/node--transaction--teaser.html.twig

Some details below, full context at https://sfgovdt.jira.com/browse/SG-605
The subtitles should be anti-aliased. They look a little heavy right now so this will help create better hierarchy with the “Get help”. If this will affect text in other places too, let me know. It’s probably OK/good.
The generic “way to get help” should not be italic. We should use italic only for special cases or notes.
Text is going past the edge of the box for hours (and maybe for other things??)
Maps should have a 1px blue L2 border 
Spacing between each component should be updated.
https://www.figma.com/file/bTWFLkGPHBnY20LvrPTKQjcW/Transactions?node-id=1%3A8

Sg 605 get help sidebar

---

config/metatag.metatag_defaults.front.yml

add a meta description tag to the sf.gov homepage

Sg 766 frontpage meta

---

config/block.block.sfgovsearchblock.yml
config/field.field.paragraph.block.field_block.yml
config/views.view.events.yml
config/views.view.services.yml
web/themes/custom/sfgovpl/README.md
web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/_mixins-fs.scss
web/themes/custom/sfgovpl/src/sass/_mixins.scss
web/themes/custom/sfgovpl/src/sass/_variables.scss
web/themes/custom/sfgovpl/src/sass/block/_block-branding.scss
web/themes/custom/sfgovpl/src/sass/components/_gtranslate.scss
web/themes/custom/sfgovpl/src/sass/components/_header.scss
web/themes/custom/sfgovpl/src/sass/components/_new-website.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-campaign.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-events.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-1mayor.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-2board.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people-3elected.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-people.scss
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-services.scss
web/themes/custom/sfgovpl/templates/node/node--landing--full.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--campaign.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--people.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--section--default.html.twig

This PR includes the following subtasks:
- SG-963 Update new website disclaimer styling
- SG-962 Update Mayor and Board of Supervisors sections on homepage
- SG-956 Increase size of SF.gov seal
- SG-957 Remove first two elements from SF.gov homepage
- SG-958 Update styling of SF.gov homepage campaign
- SG-959 Update services area on SF.gov homepage
- SG-955 Display events on SF.gov homepage

sg-955 - Homepage refresh

---

web/themes/custom/sfgovpl/README.md
web/themes/custom/sfgovpl/templates/node/node--step-by-step--card.html.twig
web/themes/custom/sfgovpl/templates/node/node--transaction--card.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--department-service-section.html.twig
web/themes/custom/sfgovpl/templates/views/views-view-unformatted--events--block-1.html.twig
web/themes/custom/sfgovpl/templates/views/views-view-unformatted--news--block.html.twig

The view template in use for the **events section** is `views-view-unformatted--events-block-topics.html.twig`, which itself extends `views-view-unformatted--events--block-1.html.twig`. I made the change in the `block-1` template directly. 
If the `block-1` template shouldn't have been modified because its `h3.title` is desired, then the `events-block-topics` will need to be modified to either a) not extend the `block-1` template, or b) alter the twig `{% block title %}` from `events-block-topics` to use the requested `h2`.

sg-965 - accessibility changes to topics

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--spotlight.html.twig

This is a proposed fix for SG-976, which you can see on pretty much any topic page with a browser window at about tablet-ish width:
| [Census 2020](https://sf.gov/topics/census-2020) | [Budget](https://sf.gov/topics/budget) |
| :--- | :--- |
| ![image](https://user-images.githubusercontent.com/113896/76124646-03bfb680-5fb0-11ea-9c22-7f159f37a702.png) | ![image](https://user-images.githubusercontent.com/113896/76125151-0b338f80-5fb1-11ea-99fa-e9c0ca6423f7.png) |
The problem is that if the aspect ratio of the image container is taller than that of the image, it shrinks vertically. This PR moves the image from the `<img>` element to a CSS background with [`background-size: cover`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size#Values), which ensures that the background …

Fix spotlight image alignment on narrow-ish screens

---

web/themes/custom/sfgovpl/src/sass/node/_node-news-card.scss
web/themes/custom/sfgovpl/templates/components/molecules/news-cards.twig

This is a proposed fix for SG-972. The source of the problem is the fixed [`height: 160px`]() causes the text to overflow when the title wraps to 4 lines or longer. We can solve that by switching `height` to `min-height`, which is _better_...
But not great. You can test this out on any page with news cards using the following snippet in your browser's JavaScript console:
```js
(() => {
const css = `.news--card.has-image { height: auto; min-height: 160px; }`
const style = document.createElement('style')
style.textContent = css
document.head.appendChild(style)
})()
```
The second part of this fix is to have news card sections use a two-column layout if there are fewer than three news items:
You can test this with the following snippet:
```js
$$('.news--card.has-image')
.map(card => …
```

Fix news item overflow with image present, use two columns if possible

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/node/_node-topic.scss

Fixes SG-1015: "See more" parent topic names break at short length on child topic pages

sg-1015 - See more links

---

config/core.entity_form_display.paragraph.form_io.default.yml
config/core.entity_view_display.paragraph.form_io.default.yml
config/field.field.paragraph.form_io.field_formio_render_options.yml
config/field.storage.paragraph.field_formio_render_options.yml
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

@hshaosf We'd like to be able to pass options to `Formio.createForm()` at runtime, on a per-form basis. (Stuff like being able to show or hide certain buttons in the [wizard](https://formio.github.io/formio.js/app/examples/wizard.html) nav, for instance.) This is an attempt to stub out the template changes that would:
1. Output the `data-options="..."` attribute as a JSON-encoded string, then
2. Parse the value as JSON and pass that to the `Formio.createForm()` function
I realize that if we encode as JSON on the template side we might have a double encoding issue — unless there's some snazzy way for Drupal to expose a JSON editor that outputs template data in object form. But in lieu of that, maybe we just take a JSON string as input (`{"foo":"bar"}`) and skip the `json_encode` filter?

Get form.io render options from template output

---

config/core.entity_form_display.node.news.default.yml
config/core.entity_view_display.node.news.default.yml
config/core.extension.yml
config/field.field.node.news.field_abstract.yml
config/field.field.node.news.field_direct_external_url.yml
web/modules/custom/sfgov_news/sfgov_news.info.yml
web/modules/custom/sfgov_news/sfgov_news.module

This PR does the following:
1.  Adds `field_direct_external_url` to the News content type. This field already contains the redirect functionality needed via `sfgov_event_subscriber` module.
2. Add a custom module named "SF Gov News" (for lack of a better place to put it), that uses States API to handle whether or not the Abstract field is required.  Prior to this PR, Abstract field was required globally.  Now, it's only required when `field_direct_external_url` is empty.

[SG-1063] Allow news node to redirect to external URL

---

.lando.yml

Improves performance, and still allows easy access to toggle xDebug with custom commands:
```
lando xdebug-on
lando xdebug-off
```
Note: Make sure to `lando restart`.

Disable xDebug globally; add commands to toggle it on/off as needed.

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

Problem as stated above, steps to reproduce: 
- Visit [https://test-sfgov.pantheonsite.io/apply-for-mini-grant](https://test-sfgov.pantheonsite.io/apply-for-mini-grant)
- Inspect the console to find the js error: `Uncaught (in promise) TypeError: Cannot read property 'cookies' of undefined`
Fixed in `paragraph--form-io.html.twig`
- Visit [http://pr-579-sfgov.pantheonsite.io/apply-for-mini-grant](http://pr-579-sfgov.pantheonsite.io/apply-for-mini-grant)
- Inspect the console to find no js error.

SG-1149: Fixes a js error when cookie is not used in form.io forms

---

web/themes/custom/sfgovpl/includes/paragraph.inc

Fixes SG-1097 by excluding the document paragraphs from gtranslate.

SG-1097 Don't allow translation of document paragraphs.

---

config/sfgov_formio.settings.yml

This pins the versions of formiojs and the SFDS theme to specific versions so that the settings persist in other environments (test-sfgov and PR deployments). @jacine and I discussed this in Slack, and my thinking is that it's better to have these in git rather than in the Drupal UI.
As for the specific versions, I think it's important to note that:
1. We're "stuck" on formiojs v4.10.4 until I can identify whatever is causing the bizarre issue with date/time input icons rendering as `[Object HTMLElement]` (citation needed!).
2. I've upgraded us to the [6.0 release of formio-sfds](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.0.0), which gives us Truss's design updates and more accessible form navigation.

Pin formiojs and theme versions

---

config/sfgov_formio.settings.yml

Here are links to the release notes for all of the versions since 6.0.2. I've noted the only release that includes a fix that's relevant to sf.gov; most of these are testing + DX improvements:
- [6.0.3](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.0.3)
- [6.0.4](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.0.4) includes an accessibility fix that properly associates most inputs with their labels
- [6.0.5](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.0.5)
- [6.0.1](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.1.0)

Upgrade formio-sfds to 6.1.0

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/components/_details.scss

The new accordions look great! I noticed, though, that on smaller viewports the background of the `<details>` element bleeds out from behind the border-radius of the `<summary>`:
This PR removes the offending white background. My first attempt at fixing this was to just remove the background from `<details>`, since `<summary>` already has one:
https://github.com/SFDigitalServices/sfgov/blob/df34989d0f341657f1b880fe43b93b32094bf415/web/themes/custom/sfgovpl/src/sass/components/_details.scss#L4
But then the content didn't have one:
So I brought the background back and added a border-radius to the `<details>` element instead. This effectively crops the element, masking out the white background:
Yes, it took me 5 commits to figure this out. Please squash this when merging. :joy:

Fix bleeding white background on service accordions

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/js/meetings.js
web/themes/custom/sfgovpl/src/sass/view/_view-meetings-filters.scss

Also fixes an issue where sf-design-system [`@extends button`](https://github.com/SFDigitalServices/sf-design-system/blob/main/src/components/04-forms/field-types/_form-fields.scss#L286) with `::before`, which was breaking the show/hide icons.

[SG-1209] Don't focus on fields after opening filters on mobile meeting list

---

config/sfgov_formio.settings.yml

This updates us to a more recent release of formio.js and bumps our theme to improve accessibility. See https://github.com/SFDigitalServices/formio-sfds/pull/83 for more info.

Upgrade formiojs to 4.11.2, formio-sfds to 6.2.0

---

.github/workflows/trigger-circleci-main.yml

Sounds loopy, but hear me out (also in comments in workflow yml):
The sfgov project uses a gitflow-ish type of workflow such that
* `main` is production ready code and hotfixes
* `develop` is the base/default to branch from for bug fixes and new features
We recently updated our circleci settings to build only for pr's because building for every commit was causing us to max our multidev limits on pantheon.  Buuut, because of our workflow above, `main` never gets built because `main` is never the compare branch for any pr.  `main` needs to get built because that's the branch that gets deployed to pantheon.  _This_ pr makes that happen by adding a github action/workflow that manually triggers a circleci build via the circleci api when `main` is pushed.
😓 
There's a circleci …

Use github action to trigger circleci build for main branch

---

web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/forms/_formio-feedback.scss
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io--feedback.html.twig

This provides a more compact version of the Feedback form above the footer on Form pages, so compare:
- Regular page: https://pr-668-sfgov.pantheonsite.io
- Form page: https://pr-668-sfgov.pantheonsite.io/node/973
Note: Most of the changes here are on the Form.io side, and when this is deployed we will need to update the [existing](https://sfds-test.form.io/feedback) form config with the [new](https://dev-sfds.form.io/feedback) one, using the [CLI tool](https://github.com/formio/formio-cli):
```bash
formio copy form https://dev-sfds.form.io/feedback https://sfds-test.form.io/feedback
```

[SG-1223] Compact version of Feedback for form pages

---

.github/workflows/lighthouse.yml
.lighthouserc.js

Okay, so I'd love to test this out on the develop branch and see if it works, because the whole poll-the-deployments-API approach is clearly not working. Here's what _should_ happen after this merges:
Every time a successful `deployment_status` event is triggered, Actions will checkout the repo at the same git SHA/ref as the deployment and run LHCI. I've had to make [another action](/sfdigitalservices/git-the-branch) to determine the right git branch from these events, since (unlike `push` events) they're not associated with a branch/ref. But it seems to work, and now instead of having a Lighthouse action run tied to every push, they only run on deployments, and the commit still gets the status:

Set up Lighthouse CI

---

config/views.view.news.yml
web/themes/custom/sfgovpl/dist/css/drupal.css
web/themes/custom/sfgovpl/src/sass/components/_news-front.scss
web/themes/custom/sfgovpl/src/sass/node/_node-news-card.scss

- Use the proper view mode when there is an image (homepage) vs not (topics, departments).
- Remove homepage-specific CSS, which as using a different layout technique.
- All the News card CSS lives in one place, and is documented.
- Change the breakpoint for when the image appears, as there is never enough room for it to look good until `$narrow-screen`.

[SG-1138] News Card Refactor

---

config/sfgov_formio.settings.yml

See https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.4.0 for more info.
@aekong This release has been tested more thoroughly and is ready to go. This supersedes #695.

Update formio-sfds to 6.4.0

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

There is a setting in the form page's form.io render options to add a css class to the block-gtranslate element, the purpose is align the translation icon on mobile version.
Fixed in `paragraph--form-io.html.twig`

SG-1245: add null check before appending css class to element

---

config/sfgov_formio.settings.yml

This bumps us two patch versions:
- [6.4.2](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.4.2) fixes state and zip inputs bumping up on smaller screens and the order of our CSS utilities in the output
- [6.4.3](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.4.3) adds U.S. states to state input lists and removes a `globalThis` reference that was breaking IE and Edge ≤ 18
See [the diff](https://github.com/SFDigitalServices/formio-sfds/compare/v6.4.1...v6.4.3) for the nitty gritty.

Update formio-sfds to 6.4.3

---

config/sfgov_formio.settings.yml

Updating formio-sfds version to 6.4.4 to support ADU launch. 
https://github.com/SFDigitalServices/formio-sfds/releases/tag/v6.4.4

Update formio-sfds to 6.4.4 to support ADU launch

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This PR adds log Amplitude events for more general timing related bits:
- `window.load` with `load_time` from the start of the form paragraph `<script>` execution to window `load` event firing, in milliseconds
- `form.load` with `load_time` from the window `load` to when the `Formio.createForm()` promise resolves, also in milliseconds
And for more specific form interactions. The below events include a `form` object with, at the very least, a `url` key indicating the form.io data source URL. Additional event data noted below is nested in the event's `form` object.
- `form.submit` before the submission is sent to form.io (no additional data)
- `form.submitDone` after successful submission (no additional data)
- `form.submitError` when a submission fails validity checks (`component` is the …

Add amplitude events for form.io forms

---

config/sfgov_formio.settings.yml

I only just realized that I forgot to upgrade to 7.0.1 in the config after updating in production on Tuesday. This release fixes a bug with a flash of un-styled content that can happen if Phrase translations take too long to load. See [the release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v7.0.1) and https://github.com/SFDigitalServices/formio-sfds/pull/145 for more information.

Upgrade formio-sfds to 7.0.1

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

While acceptance testing forms on test-sfgov, we discovered that form submissions were being aborted by mysterious errors. One in particular looked suspicious:
The error message here is not one that I would expect to be thrown inside formiojs or formio-sfds, and it occurred to me that formiojs probably wraps form submission calls in a `try/catch` block. Turns out, the offending code was something I added in #736 to dispatch form events to amplitude:
https://github.com/SFDigitalServices/sfgov/blob/433c61b1d69460996e8fe57c4d147dbc8481fe97/web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig#L143-L146
The bug is that `formData` may very well not equal `false`, but is `undefined` for the submit event handlers, which don't return anything: …

Catch form event handler errors and log them

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

for empty field values, drupal appears to send an empty array.  this was causing issues with the confirmation page redirect logic.
some notes copied from a slack convo:
> i think it has to do with this line: https://github.com/SFDigitalServices/sfgov/blob/f0d02537e37baf4da696815688fd51566cc5e158/web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig#L62
>
>if paragraph.field_formio_confirmation_url.value doesn’t have a value, the twig filters evaluate to [] (empty array).
>
>further down the file:
>https://github.com/SFDigitalServices/sfgov/blob/f0d02537e37baf4da696815688fd51566cc5e158/web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig#L200-L202
>
> since confirmationURL is `[]` and not `null` or `undefined`, `window.location = []` just …

handle empty array value for confirmation url

---

config/sfgov_formio.settings.yml

[This release](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v7.0.2) fixes some missing form translation keys in our radio/checkbox templates. I've already updated the config in prod because it's needed for a form that's going live today.

bump formio-sfds to 7.0.2

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

**UPDATE**: I'm hijacking this PR to also fix the issue of forms failing when ad blockers prevent Amplitude's JS from loading. The technique is to have the `amp()` function to log to the console _unless_ `window.amplitude` is truthy, in which case it swaps out the console logger for `window.amplitude.getInstance().logEvent()`.
As discussed with @jacine, @zakiya, and @nicolesque [in Slack](https://sfdigitalservices.slack.com/archives/C010PJ7HJR3/p1610058130031400), we don't currently have any way of tracking when forms completely fail to load from form.io. This PR attempts to address that by catching the promise that rejects when the form fails to load and fires a (newly minted) `form.loadError` event to Amplitude.
We should be able to test this by adding a form page with a bad data source …

Track form load errors, guard against ad blockers

---

config/field.field.paragraph.form_io.field_formio_confirmation_url.yml
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This adds support for a `{lang}` placeholder in form page confirmation URLs. I updated the field description, so now it looks like this when you're editing:
Here's an acceptance test:
```feature
Feature: form page confirmation URL
Scenario: It works without a "{lang}" placeholder
Given a form page
And the confirmation URL is "/my-form/confirm"
When I submit the form
Then the URL should be "/my-form/confirm"
Scenario: It works with a "{lang}" placeholder
Given a form page
And the confirmation URL is "/{lang}/my-form/confirm"
And the page is translated in Spanish
When I visit the form in Spanish
And I submit the form
Then the URL should be "/es/my-form/confirm"
```
cc: @nicolesque

Add {lang} placeholder support in confirmation URL

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This is a fast follow to #784. I was testing that PR with a newer version of formio.js that includes https://github.com/formio/formio.js/pull/3592, which introduces a `language` getter to the Webform class. Without it, `form.language` always returns `undefined`. The fix is to fall back on `form.options.language`.

Hotfix for missing form.language getter

---

.gitignore
.lando.yml
.vscode/launch.json.example
composer-manifest.yaml
composer.json
composer.lock

A [new version](https://xdebug.org/docs/upgrade_guide) of Xdebug came out last month.  The next time you rebuild your Lando instance, you will get v3. v2 settings are not compatible with v3.  You would also get Composer 2, which will not work with our code base.  This PR:
1. Updates the Xdebug settings for v3.
2. Locks Lando's composer version to 1.x.
3. Removes Twig Xdebug module. Twig tweak actually provides the ability to use `{{ drupal_breakpoint() }}`, which is basically the same thing.
We can/should still use the tooling commands to toggle Xdebug, e.g. `lando xdebug-on`.
---
1. Rebuilding your Lando instance is required: `lando rebuild -y`
2. If you use VSCode, you'll need to update the `launch.json` config. Specifically, the default port is now 9003. Here's my configuration: …

Update Lando Configuration for Xdebug 3 and Composer

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This adds a mapping of the `zh-TW` and `zh` language codes to `zh-hant` in form confirmation URLs with the `{lang}` placeholder to work around inconsistencies between Drupal, Google Translate, and Phrase.
During the first pass at testing I noticed that we don't support `/en/`-prefixed URLs, so in 1347b1e I opted to strip the `{lang}/` bit from the confirmation URL if the language is `en`.
@aekong LMK if you think this should live somewhere else. It might be good to have all of our language code mappings in one place, but I might need your help figuring out where that would be so that they're available to all of the scripts that need them. These are the other two I found:
https://github.com/SFDigitalServices/sfgov/blob/4fa402afe2c5e1badd2b71771d888e80708b2470/web/themes/custom/sfgovpl/src/j …

Alias "zh-TW" and "zh" to "zh-hant" in form confirmation URLs

---

config/sfgov_formio.settings.yml

See the release notes for the two releases since 7.0.2:
- [7.1.0](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v7.1.0)
- [7.2.0](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v7.2.0)

upgrade formio-sfds from 7.0.2 to 7.2.0

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This adds three keys to the form `submitDone` event handler that generates data for Amplitude:
1. `id` is the unique submission ID (`_id` because Mongo)
2. `form` is the unique form ID
3. `project` is the unique project ID
This should allow us to get more information about odd form submissions and figure out where invalid autocomplete values are coming from (browser, version, user journey, etc.).
🔒 **None of the submission data is included in this payload.**

Log form submission metadata in amplitude

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This is for SG-1314. My working theory is that our `form.error` events aren't structured properly—maybe because they're arrays, or they're too big?—and Amplitude is throwing them away. We're currently only collecting `form.componentError` events, which bubble up from every single component validation failure, and could include practically every single keystroke in some text/email/phone/etc. fields. 😱 
There are a couple of different places that formio.js [emits `error` events](https://github.com/formio/formio.js/search?l=JavaScript&q=emit+error):
- [`emit('error', errors)`](https://github.com/formio/formio.js/blob/v4.11.2/src/Webform.js#L1208) in [`showErrors()`](https://github.com/formio/formio.js/search?q=showErrors), which gets called in a bunch of different places, but only emits an …

Silence form.componentError Amplitude events + fix form.error payloads

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

I noticed when debugging events for #797 that the change in #790 made for some kind of awkwardly shaped event objects:
key | what it represents
:--- | :---
`form.form` | The form ID
`form.id` | The _submission_ ID
`form.project` | The ID of the project ("SFDS") in which the form lives on form.io
`form.url` | The form data source URL (unchanged)
The form and project IDs aren't really useful since we have form data source URL (`form.url`) already. This PR removes those two properties and renames `form.id`, which is both ambiguous and wrong, to `form.submission_id`.

Rename form.submitDone "form.id" key to "form.submission_id"

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This adds a `page_title` property to our `form.prevPage` and `form.nextPage` Amplitude events so that funnel analyses are easier to build and read, as reported in SG-1313.
⚠️ **Note**: page titles are whatever is stored in the form—not the panel title translations—even when viewed in English.
Also, c54e4ef replaces an arrow function (`=>`) that I added in a previous PR with the more legacy-browser-compatible `function` keyword.

Add form page (panel) title to next/prev page events

---

web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php

Instead of throwing a white screen of confusion, we'll show an error message in the body of the page.

[vaccine-sites] Gracefully fail when there's a connection timeout.

---

web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php

It looks like new languages were added via https://github.com/SFDigitalServices/vaccination-site-microservice/pull/102, which weren't accounted for in the `sfgov_vaccine` module settings.  
This pr will prevent drupal's `t` function from attempting to translate an empty string (a lang code that doesn't exist in `/config/sfgov_vaccine.settings.yml`).  
Allowing the attempt caused the exception:
```
Uncaught PHP Exception InvalidArgumentException: "$string ("") must be a string.
```

only push language with existing key

---

web/themes/custom/sfgovpl/src/js/exclude-from-gtranslate.js
web/themes/custom/sfgovpl/templates/node/node--event--card.html.twig

- Google is doing the translation of “Wednesday”. For some reason I don’t understand, if I use date(“l”) instead of just printing the markup, the accented é appears in miércoles
- I think I permanently fixed the gibberish problem on gtranslate pages. At some point I tried using the list of Drupal’s translatable string to the donottranslate list via js. Included in that list are abbreviations for days of the week like “Sa, Su, Mo…” Chaos ensued.

[SG-1351] White screen on translated pages with event cards.

---

.circleci/scripts/tests/accessibility/accessibility-scan
.circleci/scripts/tests/run-tests

Accessibility scan post-build with [@axe-core/cli](https://www.npmjs.com/package/@axe-core/cli) sometimes fails with the helpful error
```
An error occurred while testing this page.
Please report the problem to: https://github.com/dequelabs/axe-cli/issues/
```
This pr prevents those failures from failing the build in circleci and reports the scan error with the equally helpful `scan error` in slack:

Accessibility scan errors

---

config/sfgov_formio.settings.yml

[This release](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v8.1.0) adds a new component class and templates for the form.io `signature` component.

Bump formio-sfds to 8.1.0

---

config/core.entity_form_display.node.campaign.default.yml
config/core.entity_view_display.node.campaign.default.yml
config/field.field.node.campaign.field_contents.yml
config/field.field.node.campaign.field_social_media_embed.yml

Hides the instagram feed option from "Additional content" and "Social media embed" fields on the Campaign content type

SG-1422 - hide campaign instagram field from form and template display

---

web/themes/custom/sfgovpl/sfgovpl.libraries.yml
web/themes/custom/sfgovpl/src/sass/_mixins-fs.scss
web/themes/custom/sfgovpl/src/sass/_variables.scss

This PR deletes the unused 700 weight from our Google Fonts URL for the Rubik typeface. Due diligence:
1. The only instance of `700` that I found which seems relevant to font weight is the `$fw-bold` Sass variable
2. With one exception, `$fw-bold` is used only to increase the boldness of Chinese titles
3. The only exception to the above is a typography mixin named `fs-news-type`
4. There are no references to the `fs-news-type` mixin in our Sass files
I've deleted the `fs-news-type` mixin so that the only places we use `$fw-bold` are to increase the boldness of Chinese titles. See #940 for an experiment demonstrating what it would look like to normalize font weights in Rubik and Noto Sans TC, and https://github.com/SFDigitalServices/design-system/pull/16 for the first pass at bundling the …

Nix Rubik 700 weight

---

web/themes/custom/sfgovpl/src/sass/node/_node-form-page.scss

This particular bit of CSS is breaking buttons on our forms, and there's no simple way to work around it:
https://github.com/SFDigitalServices/sfgov/blob/7d2a61e4688072b53bbed96959ca09efc79a452f/web/themes/custom/sfgovpl/src/sass/node/_node-form-page.scss#L53-L55
@henryjiang-sfgov I'm also curious about [this bit of CSS](https://github.com/SFDigitalServices/sfgov/blame/4fe838fbde04d37ab32ad19e8f596567270f70aa/web/themes/custom/sfgovpl/src/sass/node/_node-form-page.scss#L14-L15) that conflicts with formio-sfds's styles:
```css
.formio-sfds .flex-auto {
flex: 1 1 auto;
}
```
Any idea what 6798c2280ef329eec7bb5ee1a48d3003caa4a5d3 (part of #579) was all about?

Delete bad form button hack

---

web/themes/custom/sfgovpl/package-lock.json
web/themes/custom/sfgovpl/package.json

This is a test of the new `btn-link` styles in https://github.com/SFDigitalServices/design-system/pull/33. I'm going to keep this as a draft until we:

Upgrade to sfgov-design-system@1.2.0

---

web/themes/custom/sfgovpl/templates/address/address-plain--location--physical--default-h4.html.twig
web/themes/custom/sfgovpl/templates/address/address-plain--location--physical.html.twig

For the case when a location address has a location name, but department and organization names are left blank.

[SG-1311] Fix problem with addresses not getting proper h4 tag

---

config/sfgov_vaccine.settings.yml
web/modules/custom/sfgov_vaccine/sfgov_vaccine.module
web/modules/custom/sfgov_vaccine/src/Form/SettingsForm.php
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-site--booking.twig

The vaccine sites microservice has [moved](https://github.com/SFDigitalServices/vaccination-site-microservice/pull/229) from Vercel to Heroku, so the URL is changing. We should get a proper CNAME (`vaccine-sites.api.sf.gov`?) and nix the `herokuapp.com` part entirely.
@zakiya I noticed that the URL is referenced in two places, so I changed it in both.

update /vaccine-sites microservice URL

---

composer-manifest.yaml
composer.json
composer.lock
config/core.extension.yml
config/embed.settings.yml
config/field.field.node.meeting.field_public_body.yml
config/field.field.node.public_body.field_subcommittees.yml
config/field.field.paragraph.other_info_document.field_file.yml
config/system.action.bulk_update_fields_on_embed_button.yml
patches/entity_reference_unpublished-media.patch

This pr adds the [Entity Reference Unpublished](https://www.drupal.org/project/entity_reference_unpublished) and the [Embed](https://www.drupal.org/project/embed) modules in order to allow users without the permission `Bypass content access control` to reference the following unpublished content:
- content types
- taxonomy terms
- media (required manual patch)
We will also need to update the reference method for every field to `Unpublished Default` or `Unpublished Media` where appropriate.

Sg 1483 ref unpublished

---

config/sfgov_vaccine.settings.yml
web/modules/custom/sfgov_vaccine/sfgov_vaccine.module
web/modules/custom/sfgov_vaccine/sfgov_vaccine.services.yml
web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
web/modules/custom/sfgov_vaccine/src/Form/SettingsForm.php
web/modules/custom/sfgov_vaccine/src/Services/VaxValues.php
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--header.twig

Exposes the header description text to be user-editable.
Also updates config to match what's currently on production, which is probably unnecessary now that the header text is coming from state

Allow editor to update vaccine sites header description

---

config/views.view.content.yml

Allow users who can access `/admin/content` to search for authors, which is already included as a field in the rendered view.

[SG-1484] Add author exposed filter to content view

---

composer.json
composer.lock

Apply patch from issue 3049127 for the Quick Node Clone project:
https://www.drupal.org/project/quick_node_clone/issues/3049127
This patch removes translations when in the process of cloning a node so that the new node created does not contain all the translation content.

[SG-1430] Do not carry over translations when cloning node

---

composer.json
composer.lock

I created a new issue in the quick_node_clone issue queue since there were no existing ones that covered this bug:
https://www.drupal.org/project/quick_node_clone/issues/3226576
Here is the patch I wrote to fix the bug:
https://www.drupal.org/files/issues/2021-08-03/get-correct-revision-3226576-2.patch

[SG-1445] Fix problem with node cloning not starting from node latest revision

---

web/themes/custom/sfgovpl/package-lock.json
web/themes/custom/sfgovpl/package.json

See sfdigitalservices/design-system#40 for more details. Here is the [cssstats-diff](https://github.com/shawnbot/cssstats-diff) report:
| key | delta | before | after |
| :--- | :--- | :--- | :--- |
| size | 96 kB | 80102 | 176097 |
| gzipSize | 12.2 kB | 10267 | 22423 |
| rules.total | 1,695 | 1332 | 3027 |
| selectors.total | 1,714 | 1481 | 3195 |
| selectors.type | 7 | 4 | 11 |
| selectors.class | 1,700 | 1474 | 3174 |
| selectors.pseudoClass | 309 | 516 | 825 |
| selectors.pseudoElement | 3 | 0 | 3 |
| declarations.total | 2,582 | 1705 | 4287 |
| mediaQueries.total | 1 | 2 | 3 |
obtained with:
```sh
npx cssstats-diff --format=markdown https://unpkg.com/sfgov-design-system@{1.3.0,2.0.0}/dist/css/sfds.css
```
I'm working on a script to report this next time, but for now it looks like …

Upgrade to sfgov-design-system@2.0.0

---

config/sfgov_formio.settings.yml

See https://github.com/SFDigitalServices/formio-sfds/pull/202 and https://github.com/SFDigitalServices/formio-sfds/pull/205 for `formio-sfds` changes since 9.1.0, and https://github.com/SFDigitalServices/formio-sfds/pull/189 for a summary of updates to `formiojs` since 4.12.1.

Upgrade form package versions: formio-sfds@9.2.1 + formiojs@4.13.2

---

web/themes/custom/sfgovpl/includes/node.inc
web/themes/custom/sfgovpl/includes/page.inc

Getting this error frequently since #1009:
```
Notice: Undefined index: view_mode in _sfgovpl_negotiate_translation() (line 1102 of themes/custom/sfgovpl/includes/node.inc).
```
This pr narrows the scope of `sfgovpl_preprocess_page` to `sfgovpl_preprocess_page__node__form_page` and provides a default value for the `$view_mode` param in `_sfgovpl_node_notranslate`

SG-1405 - hook_preprocess_page does not have view_mode available in vars

---

config/amplitude.amplitude_event.page_view.yml

This PR adds a new `content_lang` property to Amplitude page view events via the `[node:langcode]` "token". I've demoed this on test-sfgov and confirmed that it works by modifying the Amplitude configuration there (using the "SF.gov test" project key [here](https://test-sfgov.pantheonsite.io/admin/config/system/amplitude)) and finding my events in Amplitude:
~I also want to test this out on this PR's multidev to confirm that my formatting of JSON-string-in-YAML is legit.~ (It is!)
Another thing I noticed when sifting through my own events in Amplitude is that the Drupal plugin doesn't appear to expand any of the bracketed "tokens" on Drupal admin pages, which creates some noise in our event data:
This probably isn't a huge issue since we filter out logged in views in most of our analytics …

Add "content_lang" property to Amplitude page views

---

config/core.entity_form_display.node.person.default.yml
config/field.field.node.department.field_people.yml
config/field.field.node.location.field_people.yml
config/field.field.node.person.field_city_department.yml
config/field.field.node.public_body.field_board_members.yml
config/field.field.paragraph.section.field_content.yml
config/pathauto.pattern.person.yml

- disable old profile photo field
- remove profile from front page, public body, location, department (keep profile group)
- update path alias to use /profile instead of /person
- add help text to field_city_department to say “Profile will show contact information from department or public body (unless you enter another address)”

Post deploy profile configs

---

web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-campaign-resource-section.scss

If tiles are small, they don't force parent to be 100% width. So force it.

SG-1506 Fix resource tile widths when tile content is small

---

config/sfgov_vaccine.settings.yml
web/modules/custom/sfgov_vaccine/src/Controller/VaccineController.php
web/modules/custom/sfgov_vaccine/src/Form/SettingsForm.php

The goal here is to add a visible "tag" to sites that have vaccine doses for kids age 5 to 11. They should look like this:

VAX-265: Add tags to vaccination sites with kids5to11.allowed === true

---

web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-site--booking.twig
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-site.twig
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--alert.twig
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--count.twig
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--header.twig

I'm adding two `notranslate` clases to the `/vaccine-sites` page so that translators can more easily identify what needs to be (human) translated:
1. In the header (top blue banner)
2. To the outermost `<div>` for each site card, and removing the `notranslate` classes on children
3. To the "Showing {count} results" text above the sites list
4. Around the alert paragraph

Add notranslate classes to vaccine sites header + cards

---

web/themes/custom/sfgovpl/purgecss.config.js

In #1000 we started purging "unused" code from our generated CSS, which saves our users from downloading a bunch of code. Some forms (Shared Spaces in particular, cc: @JimBrodbeck) have already adopted the new spacing utilities, but they're not currently taken into account in the "content" we provide to PurgeCSS to detect which CSS is used, so they're being removed.
This PR adds a [PurgeCSS safe list](https://purgecss.com/safelisting.html) to our config that preserves the "basic" spacing utilities: any class beginning with `m` or `p`, followed by an optional direction (`t`, `r`, `b`, `l`, `x`, or `y`), then `-` and one or more digits. This matches the utilities I found in the Shared Spaces form:
```
mb-10
mr-20
mt-40
my-40
p-40
```
The regular expression is not "anchored" with `^` or `$`, …

Safelist margin + padding CSS utilities

---

.circleci/scripts/pantheon/02-init-site-under-test-clone-existing
composer.json
pantheon.yml

as part of drupal 9 upgrade, attempt to update php, db, and drush versions on pantheon via pantheon.yml first, then do the other upgrade related things (composer, configs, deprecated code, etc).

update php, db, and drush in pantheon yml

---

web/modules/custom/sfgov_utilities/sfgov_utilities.services.yml
web/modules/custom/sfgov_utilities/src/Commands/SfgovDrushCommands.php

Run `drush tmgmt_clean_xtm` to delete aborted/finished xtm/xtm_test jobs. Note that this will also attempt to delete files associated with these jobs that are not being used anywhere else, see line 670 of web/modules/contrib/lionbridge_translation_provider/tmgmt_contentapi/tmgmt_contentapi.module

SG-1572: add drush command for deleting old jobs

---

.circleci/config.yml
scripts/custom/create-amplitude-release.sh

For SG-1549. Currently our automated Amplitude releases don't have end timestamps, which makes them "stack" in the UI:
This sets their end to one second after the release, which should mark them as a point in time and prevent them from stacking. I'm also reformatting the title, setting the version to the date (similar to how we version in GitHub releases) and adding description and author fields.
You can see a preview of the release generated by this PR [on Amplitude](https://analytics.amplitude.com/sfdigitalservices/releases/project/254244), and in [this chart](https://analytics.amplitude.com/sfdigitalservices/chart/buqv0q0/edit/rbm74k0):

Make Amplitude releases end, add more info

---

.github/workflows/amplitude.yml
scripts/custom/amplitude-event.js

This is the first step of SG-1550.
The idea here is to collect some metrics on our work. I'm particularly interested in how long PRs take to review and merge, but I'm also really interested in how long CI runs and deployment to Pantheon take, so that we can better understand where we can eke out some more speed (so we can work more effectively).
GitHub Actions workflow changes don't run on pull requests, so we will need to merge this PR to start collecting events. We may need to follow up with some tweaks to the Amplitude event data, but I think this will be a good start.

Add Amplitude event logging for GitHub events

---

.circleci/config.yml

I noticed errors like [this one](https://app.circleci.com/pipelines/github/SFDigitalServices/sfgov/3826/workflows/e4e9e1be-ddb3-4d6f-8174-01ed62fd1f4b/jobs/13191?invite=true#step-102-2) since merging #1134. This fixes them! 🎉 
The problem was that CircleCI wants double quotes (I had single) in interpolations.

CI: fix composer cache key expression

---

pantheon.yml
web/private/scripts/lionbridge/lionbridge-credentials.php

This pr adds a script to 
- read lionbridge credentials from a non-vcs directory
- execute `drush config-set` to update the lionbridge config with the appropriate keys and values `after` the pantheon `sync_code` workflow completes

set lionbridge creds post config-import

---

web/private/scripts/lionbridge/lionbridge-credentials.php

#1160 resulted in an error in the pantheon `dev` environment:
```
Uncaught Error: Class 'Symfony\Component\Yaml\Yaml' not found
```
It looks like the symfony yaml component isn't available for the pantheon workflow hooks, so going back to good ol' json for the credentials file and just reading the contents to pass to `drush config-set`

drush config-set lionbridge credentials

---

pantheon.yml

For SG-1642. Per the [Pantheon docs](https://pantheon.io/docs/pantheon-yml#enforce-https--hsts):
> Use of `full` or `full+subdomains` should be treated as a commitment. HSTS headers are cached by browsers for the duration of the max-age period. If your site is unable to serve HTTPS (e.g. by moving to a host that doesn't support HTTPS), visitors will be unable to access your site.

Add "enforce_https: full" to pantheon.yml for HSTS header

---

web/themes/custom/sfgovpl/templates/components/atoms/service-card.twig

alert properties were being applied to the service/resource section when an alert was added.  this pr prevents unncessary attributes from being added to service/resource cards
**before**: [https://sf.gov/public-body/2020-census-redistricting-task-force](https://sf.gov/public-body/2020-census-redistricting-task-force)
**after**: [https://pr-1176-sfgov.pantheonsite.io/public-body/2020-census-redistricting-task-force](https://pr-1176-sfgov.pantheonsite.io/public-body/2020-census-redistricting-task-force)
|before|after|
|---|---|

fix incorrect color on resource cards

---

composer.json
config/amplitude.amplitude_event.page_view.yml

- patch amplitude to fix the missing annotation error which was preventing changes from being saved
- update the yaml config for page view event `properties` key to a string

Amplitude page view json

---

composer.json
config/amplitude.amplitude_event.page_view.yml
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io--feedback.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

It looks like something is causing previews of form page translations to get event properties in `drupalSettings.amplitude.events` that don't parse as valid JSON. The one I'm seeing is:
```js
'{"page_title":"Preview for the &quot;Filipino&quot; version of &quot;Aplikasyon para sa Gawad na Tulong sa Upa\r\n&quot;","page_url":"https://sf.gov/rent-relief-grant-application/preview-link/xdmT9PCTstIDFMDXhXb9lcERWlmmjGUiMpaxGtlY1DZPjAwzpeFJLIg8cYgUgh1ZXa7pb","content_type":"Form page","department":"", "topic":""}'
```
Specifically, in this string the `\r\n` at the end of that Drupal-generated `page_title` field is invalid JSON: the carriage return and newline characters need to be escaped (doubly, as `\\r\\n`). I'm not sure what's creating this JSON string; @aekong, any idea?
We should be using …

Form previews: use safeJSONParse() for page view event properties

---

config/core.base_field_override.paragraph.spotlight.created.yml
config/core.base_field_override.paragraph.spotlight.status.yml
config/field.field.paragraph.spotlight.field_spotlight_image.yml

A disabled spotlight image field was causing translations to break.  This pr omits the old field from translation.

disable old spotlight image field for translation

---

config/field.field.paragraph.cost.field_cost_type.yml

The chosen value of the cost type (`free`, `flat`, `range`, etc) are being translated by our translation vendor, but the input field value isn’t translated on the drupal backend.  For example, in the english translation, `range` is selected as cost type, that value is sent to lionbridge to translate to Spanish and comes back as `rango`.  But, the radio input of the value isn’t translated, so there’s a mismatch and the system won’t select the appropriate radio button automatically.
This pr prevents the cost type from being translated.  This should be ok since the cost type value isn't being used in the templates.

SG-1598 - do not translate cost type radio button values

---

config/pathauto.pattern.form_start_page.yml

Update pathauto pattern to use the token `[node:source:title]` for form pages

SG-1663 - Translated forms should not have translated URLs

---

config/pathauto.pattern.events.yml
config/pathauto.pattern.meeting.yml

Updates the pathauto url alias patterns for the `Event` and `Meeting` content type to use the new date field

SG-1709 - Meeting and event URLs does not include date (for recurring instances)

---

config/core.entity_form_display.node.topic.default.yml
config/editor.editor.sf_full_html_with_toc.yml
config/filter.format.sf_full_html_with_toc.yml
config/user.role.digital_services.yml
config/user.role.publisher.yml
config/user.role.writer.yml

* rearranges the form display for topics, resources are now above dept tagging
* updates the permission for text format `SF Full HTML with TOC` for the `Writer`, `Publisher`, and `Digital Services` user roles
this configuration is already live.  this pr serves to persist the configuration on the next production deploy

Prod config update

---

README.md
web/modules/custom/sfgov_moderation/src/StateTransitionValidation.php

The code that modifies permissions for the workflow has been disabled, but the Reviewer process functionality and "reviewer" field are still working. Writers can now set content to published at any time, not only when first creating a page.

SG-1720 - Disable Reviewer process custom permissions workflow

---

web/modules/custom/sfgov_utilities/js/sfgov_utilities_sandbox_user.js
web/modules/custom/sfgov_utilities/sfgov_utilities.libraries.yml
web/modules/custom/sfgov_utilities/sfgov_utilities.module

* adds an accordion on the login page for logging in as the different roles that exist on sf.gov
* enabled only for multidev environments, not enabled for `live` or `content`

(hopefully) make it easier to log in with different roles

---

web/themes/custom/sfgovpl/package-lock.json
web/themes/custom/sfgovpl/package.json
web/themes/custom/sfgovpl/src/sass/_base.scss

* update `sfgov-design-system` to 2.3 to bring in `accessibility` utilities (https://tailwindcss.com/docs/screen-readers)
* removes added `sr-only` class css definition
* removes extraneous `sfgov-design-system` in `devDependencies`
* updates other npm packages

SG-1702 - design system to 2.3, use sr-only class from design system

---

config/pathauto.pattern.about.yml
config/pathauto.pattern.content.yml
config/pathauto.pattern.data_story.yml
config/pathauto.pattern.departments.yml
config/pathauto.pattern.events.yml
config/pathauto.pattern.form_confirmation_page.yml
config/pathauto.pattern.form_start_page.yml
config/pathauto.pattern.information.yml
config/pathauto.pattern.locations.yml
config/pathauto.pattern.meeting.yml
config/pathauto.pattern.person.yml
config/pathauto.pattern.public_body.yml
config/pathauto.pattern.report.yml
config/pathauto.pattern.resource_collection.yml
config/pathauto.pattern.standard.yml
config/pathauto.pattern.step_by_step.yml
config/pathauto.pattern.topics.yml

Update to pathauto patterns config files to have the new syntax from the updated module
The newer version changes the ID of the pathauto selector type from
`id: node_type`
to
`id: 'entity_bundle:node'`

SG-1743 -- Update to pathauto patterns config files to have the new syntax from the updated module

---

web/modules/custom/sfgov_admin/sfgov_admin.links.menu.yml
web/modules/custom/sfgov_admin/sfgov_admin.module

The Files page is more of an information page anyways, So I created a link in the Reports section to go to the Files listing page, and I've removed the Files link from displaying under "Content" in the admin menu, and as a Tab under the "Content" section.
I moved the link to the Reports because it still provides useful information about the files that Drupal knows about, even if there is no direct editing or other functionality.
Test:
1. Clear cache.
2. Hover over the Content tab in the admin menu, and you won't see "Files" link in the dropdown.
3. Click into the Content section. You shouldn't see a "Files" Tab in the tab links.
4. Hover over Reports, and you should see a "Files" link
5. Click into the Reports section and you should see a "Files" link in the listings

[SG-803] - Moved "Files" tab from under content, to under reports to help remove confusion.

---

web/themes/custom/sfgovpl/templates/components/hero-banner-default.twig

[SG-1730] - Fix to broken img box on Services and Public body (departments) page.
Update to the hero banner template, to only print out the img tag if the banner logo url is present. Otherwise, don't print out.
**Instructions:** 
A cache clear and review /services and /departments is all that's needed.
[SG-1730]: https://sfgovdt.jira.com/browse/SG-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1730] - Fix to broken img box on Services and Public body (departments) page.

---

web/themes/custom/sfgovpl/includes/node.inc
web/themes/custom/sfgovpl/templates/node/node--department--teaser.html.twig

The setup looks for the "Go to current URL" checkbox, which forces the site to redirect to an external site.
If it finds the checkbox is checked, it adds the target attribute to the link in the department teaser template.
Testing/Implementing instructions:
1. 	Clear caches
2. 	Test any link on the Departments page, and confirm that those links that go off to external websites,
open in a new tab

[SG-570] - Setup to make department teaser links open in a new tab, if they are linked to an external site.

---

config/field.field.node.campaign.field_campaign_theme.yml

Disables the  "Theme" field translation and locks it to same values across translations.
Instructions:
1. Edit or create a new campaign.
2. Translate page, and notice that the Theme field is not available on translations edit.
3. View all translations of the campaign page and confirm that they are all the same "theme" colors in the header

[SG-1718] -- Campaign page translation issues: disable "Theme" field translation

---

web/themes/custom/sfgovpl/includes/paragraph.inc
web/themes/custom/sfgovpl/src/sass/paragraphs/_paragraph-document.scss
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--document.html.twig

This is a rebuild to the output of the document paragraph. The preprocess function now builds an array of file information
to print out in a loop on the twig template. Before the twig template was setup to print the first, and only first item of the
files field.
Instructions:
1. Clear cache
2. Review a transaction node with multiple files in a document paragraph.
3. Confirm visually that all documents print out, and thru the inspector, that the documents all list out in an unordered list.

[SG-1724] - Document paragraphs only show the first file on a multi item file field

---

web/themes/custom/sfgovpl/src/sass/components/_address.scss
web/themes/custom/sfgovpl/templates/address/address-plain--location--field-address--physical.html.twig
web/themes/custom/sfgovpl/templates/components/phone-alt.twig
web/themes/custom/sfgovpl/templates/field/field--paragraph--email-addresses.html.twig
web/themes/custom/sfgovpl/templates/field/field--paragraph--field-title--help.html.twig
web/themes/custom/sfgovpl/templates/field/field--paragraph--phone-numbers.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--phone--default.html.twig

Things to know "Cost" set to h2 instead of h3.
Get help section:
- Get help = H2
- Phone or Email or Address location title = H3
- Phone or Email owner = H4
Instructions:
1. Clear cache
2. Inspect a transaction page(s) with a phone, email, and address example and confirm they have the correct heading tags.

[SG-1745] - Fix reading order accessibility issues on "Need to know" and "Get help" section in transactions.

---

web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig

Changed profile name for persons to use H1 instead of div
Instructions:
1. Clear cache
2. Review person node (full page) and confirm name is in H1

[SG-1749] - Fix reading order accessibility issues on Profiles

---

web/themes/custom/sfgovpl/templates/components/callout.twig

Twig file had the "striptags" filter applied to the content. It was only allowing <a> tags. I changed to allow <strong> and <ul> as they are allowed by the "SF restricted HTML" formatter.
Test/Instructions:
1. 	Clear cache
2.	Edit a known callout box or create one on a transaction
3.	Edit the text to add bold or underline text.
4.	Save and observe fix.

[SG-746] -- Fix to callout description text box formatting.

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--powerbi-embed.html.twig

Adjustment to the power bi embed template, to give a better iframe size ratio. This ratio should help get the width of the embed to fit better.
Instructions:
1. clear cache
2. visit pages with power bi embeds and confirm that the width of the embed matches the embed footer

[SG-1723] - Adjust size calculations for powerBI embeds

---

web/modules/custom/sfgov_admin/sfgov_admin.module

This setup should force body type fields, with only 1 allowed type of formatter, to reapply the correct
formatter on a nodes edit page, so that it doesn't break the editorial workflow.
It works on main level body type fields thru a node_form_alter hook, and on body fields in paragraph subforms thru a paragraph_widget_form_alter hook.
Testing instructions:
1. Clear cache
2. Review any known pages that have the broken body formatters, like transaction nodes.
3. Confirm that upon going to that nodes edit page, that no body type fields have a broken formatter and don't cause an error on save.

[SG-1737] - Automatically re-sync body type fields with the formatter that should be applied to them

---

web/themes/custom/sfgovpl/src/sass/node/_node-report.scss

Set styling for hr tags in reports (3px solid #e9e9e9 or light gray color)
Instructions:
1. Clear cache
2. Visit report with hr tags in content and confirm that the style matches 3px solid #e9e9e9 (light gray color)

[SG-1769] - Style for horizontal rules

---

config/core.entity_form_display.node.department.default.yml
config/core.entity_view_display.node.department.default.yml
config/core.entity_view_display.node.department.location_page.yml
config/core.entity_view_display.node.department.search_index.yml
config/core.entity_view_display.node.department.teaser.yml
config/core.entity_view_display.node.department.title.yml
config/field.field.node.department.field_archive_date.yml
config/field.field.node.department.field_archive_url.yml
config/field.field.node.department.field_req_public_records.yml
config/field.storage.node.field_archive_date.yml
config/field.storage.node.field_archive_url.yml
web/modules/custom/sfgov_departments/sfgov_departments.module
web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig

Added 2 new fields to departments:
- Archive URL (field_archive_url)
- Archive date (field_archive_date)
Setup output next to the Request public records output (at the bottom of the content).
Instructions:
1. Clear cache
2. Import configuration
3. Confirm that the 2 new fields are added to departments by going to the Department content type
4. Edit an existing department or create a new one
5. Set the archived url and date values
6. Confirm they display as desired.

[SG-1746] - Link to archive sfgov.org from department home pages

---

web/themes/custom/sfgovpl/includes/node.inc

#SG-1814
The text format sf_restricted_html was being applied to the trimmed teaser of the bios, and is not setup to handle br tags, which caused
extra paragraph tags to be generated for the output. these were causing the extra spacing on the trimmed display. The expanded content was
rendered using full_html so it was not generating the break tags or extra paragraph tags. That is why the two content sets appeared different
when it was collapsed and expanded.
Instructions
1. Make sure caches are cleared
2. Review a bio with expanding bio content.
3. Confirm that the content no longer has extra spacing.

[SG-1814] -- Extra spacing in bios trimmed "teaser" content caused by extra p and br tags

---

config/field.field.node.campaign.field_logo.yml
web/themes/custom/sfgovpl/templates/layout/page--node--campaign.html.twig

SG-1810
* enables and requires the alt text field for campaign content type logo
* updates corresponding twig template to add the `alt` attribute to the image markup

SG-1810 - enable alt text for campaign logo

---

web/themes/custom/sfgovpl/src/sass/_base.scss
web/themes/custom/sfgovpl/src/sass/_mixins.scss

SG-1756
* update focus outline color to black for light backgrounds
* add more dark background elements for white focus outline

SG-1765 - update focus outline color for dark and light backgrounds

---

web/themes/custom/sfgovpl/templates/node/resource_collection/node--resource-collection--full.html.twig

SG-1794
* Updates resource collection template to check that legacy document sections have content before rendering Documents title

SG-1794 - Resource collection sometimes has duplicate title on Document sections

---

config/user.role.digital_services.yml
config/user.role.publisher.yml
config/user.role.writer.yml

SG-1824
* enable quick node clone for reports for writer, publisher, and ds roles

SG-1824 - Allow writers, publishers, and DS permission levels to duplicate "reports"

---

web/themes/custom/sfgovpl/templates/components/hero-banner-color.twig

#SG-1842
Fix to alignment issues by adding the proper container class to header-banner template

#SG-1842 -- Fix to alignment issues by adding the proper container class to header-banner template

---

config/core.entity_form_display.block_content.alert.default.yml
config/core.entity_form_display.node.department.default.yml
config/core.entity_form_display.node.event.default.yml
config/core.entity_form_display.node.form_confirmation_page.default.yml
config/core.entity_form_display.node.information_page.default.yml
config/core.entity_form_display.node.location.default.yml
config/core.entity_form_display.node.person.default.yml
config/core.entity_form_display.node.public_body.default.yml
config/core.entity_form_display.node.step_by_step.default.yml
config/core.entity_form_display.paragraph.campaign_spotlight.default.yml
config/core.entity_form_display.paragraph.featured_item.default.yml
config/core.entity_form_display.paragraph.resources.default.yml
config/core.entity_form_display.paragraph.spotlight.default.yml
config/core.entity_form_display.resource.resource.default.yml

Setup character limited fields to not force truncation if translations are over character limit.
#SG-1828
This should help keep html tags from being added/processed in text fields with character limits, especially plain text items. Don't know if this will fix existing issues, but should help prevent them from occurring with future translations.
Import config and clear caches

SG-1828 -- Setup character limited fields to not force truncation if translations are over character limit.

---

config/core.entity_view_display.node.campaign.default.yml

SG-1890 - About sections on campaign pages are incorrectly set to trimmed/600 characters
This changes the output to default print all.
Instructions:
config import
clear caches

SG-1890 - About sections on campaign pages are incorrectly getting trimmed

---

config/core.entity_view_display.location.physical.address_plus_notes.yml
config/core.entity_view_mode.location.address_plus_notes.yml
web/themes/custom/sfgovpl/templates/eck/eck-entity--location--physical--address-plus-notes.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--in-person-location.html.twig

SG# 1872
Setup new view mode for address with notes, apply view mode to "in_person_location" address output template.
Config import
Clear caches
Review locations added to sidebars

SG# 1872 --  Allow notes to be output with addresses in sidebars

---

config/core.entity_view_display.node.campaign.teaser.yml
web/themes/custom/sfgovpl/includes/field.inc

SG-1894
This setup changes the way it grabs the summary from an About section. The character length was increased to potentially grab a larger paragraph, and then a snippet was added to try to pull out the first <p></p> content in the about text. This will need to be checked, and maybe some About content will still need to be edited, in order for this to best work for all cases.
Instructions:
- Clear cache
- Visit a information page, or any type that allows for campaigns to be added to the Resource sidebar
- Confirm that the text is no longer cutoff
Note:
- Edit any campaign about sections to make sure the first about paragraph fits in the character limits.

[SG-1894] - Truncation in a description when a campaign is used in Related.

---

web/themes/custom/sfgovpl/includes/paragraph.inc

SG-1887
The resource entity external resource has a url field. It was not rendering the url correctly if the url was referencing an internal page. This update passed the content the right Url methods to generate a proper url
Instructions:
Clear cache

[SG-1887] -- Internal linking in an external resource not working

---

config/pathauto.pattern.data_story.yml
config/pathauto.pattern.locations.yml

Data stories and location nodes set to have pathauto patterns follow url naming conventions
Instructions:
- Clear cache
- Via the content admin page, Bulk resave all location and data story nodes to trigger the pathauto updates
- Confirm that a translated data story follows the url pattern for a translation

[SG-1907] -- Data stories and location nodes set to have pathauto patterns follow url naming conventions

---

web/themes/custom/sfgovpl/includes/node.inc

SG-1915
Agency nodes that are in draft state, with no existing published version accessible to the public, are now set to not display in the about section (under the divisions/subcommittee section) It does this by checking the current moderation state of the division, and if it is "draft" then it does not allow it in the list. It applies this check for all users and roles, so not even admins will see the draft link.
Instructions:
Cache clear
Create and new agency and only assign to draft state (DO NOT publish any state for this test agency) Add this draft agency to the about section of an agency Review this page as any user (admin, logged in, anonymous, private browser). The link to the test draft agency should not display
NOTES: there are comments in the code for if this ever needs to …

[SG-1915] -- Do not show "draft" agency pages on the Division list.

---

web/themes/custom/sfgovpl/templates/components/alert.twig
web/themes/custom/sfgovpl/templates/components/vaccine/vaccine-widget--alert.twig
web/themes/custom/sfgovpl/templates/misc/vaccine-widget.html.twig

[SG-1916]
Applied yellow background to the alert for the /vaccine-site page
[SG-1916]: https://sfgovdt.jira.com/browse/SG-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1916] -- Fix alert background color on vaccine-site page

---

config/sfgov_formio.settings.yml

This is primarily a CSS maintenance release to work around issues with this repo's purge-css safelist not working as expected. There are breaking changes, but they're downstream and will only affect individual forms with outdated utility classes. See the [release notes](https://github.com/SFDigitalServices/formio-sfds/releases/tag/v10.0.0) for more info.
@aekong FYI, I've already updated the [form.io config](https://sf.gov/admin/config/services/sfgov_formio) on sf.gov 🪄

Upgrade formio-sfds to v10.0.0

---

web/themes/custom/sfgovpl/includes/block.inc
web/themes/custom/sfgovpl/src/sass/node/_node-campaign.scss
web/themes/custom/sfgovpl/templates/layout/page--node--campaign.html.twig
web/themes/custom/sfgovpl/templates/node/node--person--card.html.twig

SG-1933 - add header back to campaign
SG-1936 - add `aria-hidden` attribute to `visually-hidden` elements

SG-1933, SG-1936 - accessibility updates

---

web/modules/custom/sfgov_about/sfgov_about.install

SG-1909
Migrate the downloadable resources into the new About US section. Update hook looks at all public bodies with downloadable file paragraph types, searches for an about page that references to that public body, and then copies over the DF paragraphs over to that about page. According to a test db run, there were about 6 about pages updated. Live will have more as recently all public bodies were updated to have a corresponding about page.
Instructions:
Clear cache
Run database updates (updatedb)
Notifications of all updated content will show in terminal messaging and in drupal logs.

[SG-1909] -- Migrate the downloadable resources into the new About us section

---

web/themes/custom/sfgovpl/src/sass/_mixins.scss
web/themes/custom/sfgovpl/src/sass/node/_node-report.scss

SG-1681
Highlight pull quotes (blockquote) on the body field of report nodes.
Instructions:
- Clear cache
- Add a quote to a test report node or find an existing report node with an existing blockquote
- Confirm style change

SG-1681 -- Highlight pull quotes (blockquote) on the body field of report nodes

---

web/themes/custom/sfgovpl/src/sass/components/_table.scss

SG-1929
Add borders to both row headers and column headers for tables in wysiwgs
Instructions:
- Clear cache
- Visit page or create page with a table. Make sure headers are added to the table.
- Confirm style updates

[SG: 1929] -- Add separating borders to table headers

---

web/modules/custom/sfgov_doc_html/js/docsearch.js
web/modules/custom/sfgov_vaccine/js/filter_sites.js
web/themes/custom/sfgovpl/src/js/back-to-top.js
web/themes/custom/sfgovpl/src/js/data-story.js
web/themes/custom/sfgovpl/src/js/dept-homepage.js
web/themes/custom/sfgovpl/src/js/toc.js
web/themes/custom/sfgovpl/src/sass/_base.scss
web/themes/custom/sfgovpl/src/sass/_search.scss
web/themes/custom/sfgovpl/templates/components/header.twig

SG-1928
Set animation in all theme and custom module javascript to first determine if motion is reduced, and then set animation speeds accordingly.
Set most animations in css to try to respect reduced motion. Not sure if all animations have been found.
Instructions
- Clear cache
- Review "back to top" functionality and "table of content jumping" on reports (and any other node type with table of content menus.
- Set your OS to reduce motion/animation.
- Review previous functionality again and confirm its following the OS settings.

[SG-1928] -- Set Sf.gov to respect prefers "reduced" motion/animation.

---

web/themes/custom/sfgovpl/src/sass/node/_node-dept.scss
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--thing-to-know--department-paragraph.html.twig

SG-1941
New class and css applied to Things to know items on agency pages
Instructions:
- Clear cache
- Visit an agency with a meetings section and things to know items
- Confirm that paragraphs have better spacing between them. May have to add test content to fully test.

[SG: 1941] -- Adjust paragraph spacing in Meetings:Things to know items on Agency/Department pages

---

web/themes/custom/sfgovpl/includes/node.inc

SG-1947
This fixes the Part of tagging setup that finds resources that make reference to a data story, and then prints that reference on the data story. The issue was that past versions of the content made it looked like it still referenced content. This fix adds a double check to make sure the latest version of the resource does indeed still reference back to the data story we are on.
Instructions
- clear cache
- open a data story with multiple "Part of..." tags and open the resources in those tags in separate tabs
- edit one of the resources to not reference back to the data story and save.
- review the data story and confirm that the resource is now removed from the "Part of..." element.

[SG-1947] -- Fixed Data story "Part of..." tagging in the header.

---

config/field.field.node.department.field_agency_sections.yml
web/modules/custom/sfgov_departments/sfgov_departments.module

SG-1902
If the Agency section title is set to "None", then on save of the agency, any divisions and subcommittee values will be removed from the node.
Instructions:
- Clear cache
- Visit an agency node
- If it has Agency divisions or subcommittees, then set the agency section title to None.
- Save the node, and then go back to the Edit page for the node.
- Confirm that any divisions and subcommittees are removed from the Agency section.

[SG: 1902] -- Remove Agency section divisions and subcommittees if the section title is set to None

---

web/modules/custom/sfgov_utilities/sfgov_utilities.module

SG-1945
Programmatically removed option for H1 tags to be allowed in Report node wysiwygs. That particular wysiwyg uses the sf_full_html_with_toc format. Setup will allow for future tweaking on other formats if needed.
Instructions:
- Clear cache
- Create a new report or visit an existing one
- Confirm that H1's are not allowed in the wysiwyg.

[SG-1945] -- Report node wysiwyg should not allow H1 tags

---

config/field.field.node.department.field_direct_external_url.yml
config/field.field.node.news.field_direct_external_url.yml
config/field.field.node.person.field_direct_external_url.yml
config/field.field.node.transaction.field_direct_external_url.yml

SG-1944
Updated the label and help text for the "Direct external link" field to be: label: Redirect this page to
help text: (Any pre-existing text). Type in an SF.gov page title to look up, or enter an external URL.
Instructions:
- Clear cache
- Visit an Agency, News, Profile and Transaction node to confirm the field label change.

[SG-1944] -- Update the label/help text for Direct external link field.

---

config/views.view.content.yml

SG-1948
Removed public body nodes from the main content overview admin page. Moved to a separate tab that is only visible by administrators.
Instructions:
- Cache clear
- Confirm that public bodies are not searchable on the main content admin tab
- Confirm that anyone with administrator role can view Public bodies tab.

[SG-1948] -- Remove public bodies from content overview admin page

---

web/modules/custom/sfgov_doc_html/templates/docsearch.html.twig

SG-1935
The TOC isn't contextually useful or helpful for a screen reader. Aria hidden and tabindex of -1 were added to force screen readers to ingnore the input.
Instructions:
- Clear cache
- visit a TOC page, like /reports/november-2021/digital-accessibility-and-inclusion-standard
- try to tab into the TOC form, or activate a screen reader tool and try to keyboard/tab nav into the TOC input. It should be skipped.

[SG-1935] -- Block/Suppress functionality of TOC from screen readers

---

web/themes/custom/sfgovpl/purgecss.config.js
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--department-service-section.html.twig

SG-1946
On mobile display, the accordions in service sections, like on departments/agencies and topics, need to be bolder (font: 600) Changed tailwind config to allow for versions of font-regular, font-medium, and font-light for different breakpoints.
Instructions:
- clear cache
- visit a topic or department/agency with a service section (with accordions) and confirm that styling is working.

[SG-1946] -- Service section accordions need to be bold on mobile

---

config/field.field.node.form_page.field_formio_json_content.yml
web/modules/custom/sfgov_translation/sfgov_translation.module

SG-1962
Removing the field helps to remove the duplication of translatable content occurring on lionbridge source translations.
Clear cache
Submit a test job to lionbridge
Confirm in either the UI or in the export that the large formio json content string no longer appears in the source, and that the translation still works

[SG-1962] -- Removed the formio json content field from the translation services sources

---

web/themes/custom/sfgovpl/templates/node/node--department--full.html.twig
web/themes/custom/sfgovpl/templates/node/node--topic--full-template-1.html.twig
web/themes/custom/sfgovpl/templates/node/node--topic--full-template-2.html.twig
web/themes/custom/sfgovpl/templates/node/node--topic--full-template-3.html.twig

SG-1955
Goal:
- If there upcoming events, show the full teaser display with a more events link.
- If there are no upcoming events, but there are past events, display the "No upcoming events" message with the more events link.
- If there are no upcoming or past events, do not display the more events link.
Instructions
- Clear cache
- Review agency and topic nodes, each with confirmed upcoming events, no upcoming and past events, and with neither upcoming or past events.

[SG-1955] -- Don't display events on agencies/topics if no upcoming and no past events

---

config/views.view.content.yml

SG-1954
Config import and review the meetings tab in the content admin section.

[SG-1954] -- Add agency filter to meetings content admin view.

---

web/modules/custom/sfgov_departments/sfgov_departments.module

SG-1964
Fix related department field on transaction nodes to add any parent agencies/departments along with manually applied related agencies/departments.
Instructions:
- Clear cache
- Edit transaction or create a new one
- Add a "Related department" item, one with a known parent department
- Confirm it adds any parents to the field with the message.
- Save and confirm that all works
- Re-edit and remove, change, or add new items to double check for any oddities that may cause issues.

[SG-1964] -- Fix related department field auto parent agency addition on transaction nodes.

---

config/toc_api.toc_type.default.yml

SG-1969
Better default table-of-content settings. 
Changed to only need 1 highest item to build out. 
Changed to except up to h4.
Changed to responsive setup.
Instructions
- Clear cache
- Observe pages and confirm proper changes

[SG-1969] -- Better TOC default settings

---

web/themes/custom/sfgovpl/includes/field.inc
web/themes/custom/sfgovpl/sfgovpl.theme
web/themes/custom/sfgovpl/templates/components/hero-banner-color.twig
web/themes/custom/sfgovpl/templates/field/field--paragraph--field-owner--phone.html.twig
web/themes/custom/sfgovpl/templates/field/field--paragraph--field-title--email.html.twig

[SG-1965]
Setup different title/label type fields to remove "&nbsp;" from the frontend output.
Instructions:
- Clear caches
- Check content admin page and search for any title with "&nbsp;"
- If any appear, visit that page and see if it displays on the frontend.
[SG-1965]: https://sfgovdt.jira.com/browse/SG-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1965] -- Setup different title/label type fields to remove "&nbsp;" from the frontend output.

---

config/core.entity_form_display.node.department.default.yml
config/core.entity_form_display.node.event.default.yml
config/core.entity_form_display.node.location.default.yml
config/core.entity_form_display.node.meeting.default.yml
config/core.entity_form_display.node.person.default.yml
config/core.entity_form_display.node.public_body.default.yml
config/core.entity_form_display.paragraph.in_person_location.default.yml

SG-1960
Instructions:
- Cache clear
- Check on some of the content add pages and confirm that the "edit" button is removed from the address embeds

[SG-1960] -- Remove "edit" button from address embeds

---

config/toc_api.toc_type.default.yml
config/user.role.digital_services.yml

SG-1974
* reconfigures table of contents default settings to generate for h2 and h3 only

SG-1974 - go back to toc for h2 and h3 only

---

web/modules/custom/sfgov_utilities/sfgov_utilities.install
web/modules/custom/sfgov_utilities/sfgov_utilities.module

SG-1989
Agency pages are creating infinite redirects when the translations are added or updated.
To reproduce bug on current site:
1. Create a new agency page in English and save.
2. Node should have a URL like `/department/[title]`
3. A news listing page is automatically created for it under `/news/[title]`
4. Add a node translation for the agency.
5. BUG: the news listing page now redirects to: `/news/[agency-nid]` instead of`/news/[title]`
6. Edit the same translation and save.
7. BUG: the news listing page now creates a redirect loop and is unavailable.
This PR should fix that.

[SG-1989]: News list view gets redirect loop

---

web/themes/custom/sfgovpl/src/sass/_base.scss

[SG-1982]
Figure margins are incorrect.
Inline (left and right) margins need to be set to 0.
[SG-1982]: https://sfgovdt.jira.com/browse/SG-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1982] -- Figure margins are incorrect.

---

web/themes/custom/sfgovpl/templates/node/node--about--full.html.twig

[SG-1990]
Set the titles for "About" content type nodes to be translatable.
The title is hard-set in the template and just needed to have the translation function applied
[SG-1990]: https://sfgovdt.jira.com/browse/SG-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1990] -- Set the titles for "About" content type nodes to be translatable.

---

composer.json
patches/undefined-values-in-fielduitable-prerender.patch

[Fix]
Custom patch to address a php error involving undefined index values that is killing the "Manage Form Display" pages for media, taxonomy term, eck, and paragraph entities.
An undefined value for #value and #region_callback caused a php error in the 'call_user_func_array' function in FieldUiTable.php

[Fix] -- Patch to address a php error involving undefined index values on "Manage Form Display" pages

---

.gitignore
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

For PUBX-313, this update to our form.io template to editing previously submitted form.io submissions. Here's how it works:
1. When we create a form in form.io, we add a button that triggers saving the submission as a draft
1. We receive a webhook with the submission id (`_id`, specifically) and send a draft confirmation email with a "magic link"  to the form's URL appended with `?submission={{ _id }}` in the email template
1. If the form page finds a `submission` query string parameter, it appends `/submission/{submission}` to the form URL, which tells form.io to load that submission for editing
You can see how this works in [the original CodePen](https://codepen.io/shawnbot/pen/zYayWNa) and @fwextensions's [CodePen](https://codepen.io/fwextensions/pen/XWxeNNq?submission_id=64532608441c66 …

Enable form.io submission editing on form pages

---

config/core.entity_form_display.paragraph.social_media.default.yml
config/core.entity_view_display.paragraph.social_media.default.yml

[SG-2002]
Disable mastadon field on social media paragraphs, on agency nodes. Will be re-enabled in future.
[SG-2002]: https://sfgovdt.jira.com/browse/SG-2002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2002] -- Disable mastadon field on social media paragraphs, on agency nodes.

---

web/modules/custom/sfgov_admin/sfgov_admin.module
web/modules/custom/sfgov_admin/src/Plugin/Field/FieldWidget/SfgovParagraphsWidget.php
web/modules/custom/sfgov_alerts/sfgov_alerts.module
web/modules/custom/sfgov_formio/sfgov_formio.module

[SG-2000]
Hide the language selector for non-admin editors (writers and publishers) on specific content types.
Content types include:
- Transactions
- Location
- Campaign
- Department table
- About
- Data Story
- Topic
- Basic Page
- SF.gov Landing page
Also added some checks on strip_tags to make sure that the function always receives non-empty content. In some cases, NULL gets passed to strip_tags and causes notices and warnings
[SG-2000]: https://sfgovdt.jira.com/browse/SG-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2000] -- Hide the language selector for non-admin editors.

---

config/core.entity_form_display.paragraph.public_body_profiles.default.yml
web/modules/custom/sfgov_profiles/sfgov_profiles.module

[SG-2003]
The position field is not longer appearing in the agency page. Moved the start and ending field to disabled on the paragraph type. Commented out code that was causing the position and type field to be hidden.
[SG-2003]: https://sfgovdt.jira.com/browse/SG-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2003] -- The position field is not longer appearing in the agency page

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

This is currently being worked around with some code in the OOC forms that manipulates the event listeners array directly, but it would be better for this code to do the right thing.

Prevent the form page from showing a confirmation when a draft is saved

---

web/themes/custom/sfgovpl/templates/components/person-card.twig
web/themes/custom/sfgovpl/templates/node/node--person--card.html.twig

[SG-2019]
Changed the output of people card images to render a specific image style, rather that just rendering the original image, which could be very large.
Instructions
- clear cache
- Reload homepage and view that the image used in the mayor profile, and other profiles use a smaller image with the profile image style url
[SG-2019]: https://sfgovdt.jira.com/browse/SG-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2019] -- Changed the output of people card images to render a specific image style.

---

web/themes/custom/sfgovpl/templates/node/node--event--full.html.twig

[SG-1369]
Remove duplicate publication status bars on event full pages
Event full pages render the content moderation bar twice (header and just above body field). The content moderation field needed to be added to the list of items to not render in the content variable on the template. This item is specifically called out to be rendered in the header, so it does not need to be included in the generic content render.
Instructions
- clear cache
- visit any draft/unpublished event node as an editor
- confirm that the moderation bar only renders once
[SG-1369]: https://sfgovdt.jira.com/browse/SG-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1369] -- Remove duplicate publication status bars on event full pages

---

web/modules/custom/sfgov_departments/sfgov_departments.module

[SG-2014]
Update "Department" column label on content admin to be "Related Agency" (or "Agency" depending on filtering status)
Instructions:
- clear cache
- visit content admin page and observe change to column label
- filter type by "agency" and observe new label on same column
[SG-2014]: https://sfgovdt.jira.com/browse/SG-2014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2014] -- Update "Department" column label on content admin

---

web/themes/custom/sfgovpl/src/js/exclude-from-gtranslate.js

[SG-2007]
Changed "exclude from gtranslate" strings to only prevent translation of "Breed" when there is at least 1 space before the word.
This should prevent file names and urls with breed in the string from being wrapped in a gtranslate span. That span is what caused the display oddities to occur.
[SG-2007]: https://sfgovdt.jira.com/browse/SG-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2007] -- Changed "exclude from gtranslate" strings to only prevent translation of "Breed" when there is at least 1 space before the word.

---

config/core.entity_form_display.node.person.default.yml
config/core.entity_form_display.paragraph.public_body_profiles.default.yml
config/core.entity_form_display.paragraph.public_body_profiles.profile_position.yml
config/core.entity_view_display.node.person.default.yml
config/core.entity_view_display.paragraph.public_body_profiles.default.yml
config/core.entity_view_display.paragraph.public_body_profiles.profile_position.yml
web/themes/custom/sfgovpl/src/sass/node/_node-person.scss
web/themes/custom/sfgovpl/templates/field/field--node--field-profile-positions-held.html.twig
web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig

[SG-2013]
[SG-2012]
[SG-2010]
Profile content type/paragraph type changes
- Removed profile type field from Profile content type
- Removed support for city/external employee type. This required some changes to how the templates work for content output
- Appointment years are removed from output.
Instructions:
- clear cache
- config import
- Review profiles with different content and setups to see how things look.
- Create new profile to test out all content field.
[SG-2013]: https://sfgovdt.jira.com/browse/SG-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SG-2012]: https://sfgovdt.jira.com/browse/SG-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SG-2010]: …

[SG-2013] [SG-2012] [SG-2010] -- Profile content type/paragraph type changes

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--cost.html.twig

[SG-1999] 
"Free" cost option for Transaction pages not translatable
[SG-1999]: https://sfgovdt.jira.com/browse/SG-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1999] -- "Free" cost option for Transaction pages not translatable

---

web/themes/custom/sfgovpl/templates/paragraphs/paragraph--campaign-spotlight.html.twig
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--spotlight.html.twig

[SG-2020]
Responsive image work
Set Spotlight and Campaign Spotlight image output to use a defined image style to make sure that a smaller, more appropriate sized image is in place, rather than allow the original image which could be huge.
Instructions
- Clear cache
- visit a page where a spotlight can be added
- Add a spotlight with a large sized image and save
- Confirm that a processed version of the image is output and is smaller than the original
- Repeat for campaign spotlight
[SG-2020]: https://sfgovdt.jira.com/browse/SG-2020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-2020] -- Responsive image work

---

config/field.field.node.information_page.field_information_section.yml

[SG-1823]
Add "Callouts" to Information pages
Instructions:
- Clear caches
- Edit or add an information page
- Confirm that "Callouts" can be added to Information pages.
[SG-1823]: https://sfgovdt.jira.com/browse/SG-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1823] -- Add "Callouts" to Information pages

---

web/modules/custom/sfgov_about/sfgov_about.module
web/themes/custom/sfgovpl/includes/views.inc

[SG-1997]
Set "See more news" and "Learn more about us" to translatable.
Instructions:
- Clear cache
- Go to the UI translation interface section, and search for the strings "See more news" and "Learn more about us"
- Confirm that they appear and are translatable.
[SG-1997]: https://sfgovdt.jira.com/browse/SG-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1997] -- Set "See more news" and "Learn more about us" to translatable

---

web/themes/custom/sfgovpl/templates/components/card.twig

Adding display block to cards so when on mobile they card border/background do no break SG-2030

feat: mobile card fix

---

web/themes/custom/sfgovpl/includes/node.inc
web/themes/custom/sfgovpl/templates/node/node--person--full.html.twig

[SG-1813]
Remove duplicated positions/departments on profiles.
Instructions:
- Clear cache
- Visit several profile pages
- Confirm that there are no redundant outputs of past held departments, compared to current position
[SG-1813]: https://sfgovdt.jira.com/browse/SG-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SG-1813] -- Remove duplicated positions/departments on profiles.

---

.circleci/scripts/pantheon/02-init-site-under-test-clone-existing
.circleci/scripts/saml/saml-dependencies
.github/workflows/checks.yml

some changes to accommodate flipping on [pantheon sra](https://docs.pantheon.io/guides/secure-development/secure-runtime-access):
* `terminus auth:login` before running any terminus commands
* **additional step not in this pr**: create a new ssh key pair between circleci and pantheon.  some terminus commands require this (eg `rsync`)

updates to handle pantheon sra (secure runtime access)

---

config/block.block.editorsurvey.yml

SG-2091
config export to disable editor survey block by default

SG-2091 - disable editor survey block

---

composer-manifest.yaml
composer.json
composer.lock

SG-1234
upgrading to Token 1.13 broke the smart date tokens.
issue conversation here: https://www.drupal.org/project/smart_date/issues/3402367

chore: downgrade token to 1.12 to fix busted smart date range tokens

---

config/filter.format.plain_text.yml
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--resource-node.html.twig

SG-2119
* bring back rendered text for resource sections (do not `striptags`)
* disable automatic convert URLs into links for plain text format

SG-2119 - disable automatic url linking

---

web/themes/custom/sfgovpl/src/sass/components/_video-embed.scss
web/themes/custom/sfgovpl/src/sass/node/_node-report.scss

SG-2139
use `auto` for overflow instead of `scroll` for potentially layout-breaking tables on report pages

SG-2139 - use auto instead of scroll for x overflow

---

config/extlink.settings.yml

Config export from live, updates whitelist domain for `www.sf.gov`

SG-2127 - external link module config from production

---

web/modules/custom/sfgov_utilities/sfgov_utilities.module

hotfix from prod because of cron error for deprecated method of querying

fix: accessCheck for sfgov_utilities

---

web/modules/custom/sfgov_api/src/Plugin/SfgApi/Node/Transaction.php

During the test migration, discovered a couple things that this PR addresses:
* Order of the Transaction step fields
* Adding the title to the "step other field" in the Wagtail response
https://sfgovdt.jira.com/browse/CMS-347

Bugfix: Migrate transaction content type

---

.github/workflows/checks.yml
.vscode/settings.json
package-lock.json
web/themes/custom/sfgovpl/.browserslistrc
web/themes/custom/sfgovpl/babel.config.js
web/themes/custom/sfgovpl/sfgovpl.libraries.yml
web/themes/custom/sfgovpl/src/js/formio-form-page.js
web/themes/custom/sfgovpl/templates/paragraphs/paragraph--form-io.html.twig

For EPR-1294, this updates the JavaScript on our form pages to send Google Analytics / Tag Manager events (honestly, I still  don't quite understand the distinction). To make this less painful, I've pulled the form initialization out of the page template and into a separate JS file. It's not very legible, but [here's the diff](https://gist.github.com/shawnbot/b49f937e57bffa049b4332ad2a0dbd41) between the JS portion of the template and the new file.
The `measure()` function, which is local to the form initialization code, supports a couple of different call signatures:
1. `measure('foo')` just sends an event named `form.foo` (the first argument is a string, which gets a `form.` prefix)
2. `measure('foo', { some: 'value' })` sends the event with additional variables (specific to that event) …

feature: form analytics

---

config/system.site.yml

I noticed in the [site settings](https://www.sf.gov/admin/config/system/site-information) that the site's default "from" address is set to Josh's email. This changes it to `noreply@sfgov.org`. I've noticed that there are a couple of [other addresses](https://github.com/search?q=repo%3ASFDigitalServices%2Fsfgov%20%40sfgov.org&type=code) that we may want to look at, too (but not in this PR).

fix: set site "mail" setting to noreply@sfgov.org

---

web/modules/custom/sfgov_api/src/Payload/PayloadBase.php
web/modules/custom/sfgov_api/src/Plugin/SfgApi/Paragraph/Button.php

- Add in screen reader field for text buttons to API so the field can be migrated
- Add in a check for the isPublished flag as not all nodes seem to have that information
https://sfgovdt.jira.com/browse/CMS-349

bugfix(CMS-349): Add missing field to API and make API more resilliant

---

web/modules/custom/sfgov_api/src/Plugin/SfgApi/Media/File.php

Step 1:
Make two additional fields available for slurping up via the API: Direct URL to the file and Indirect (node file entity) URL to the file.
https://www.sf.gov/sfgov-api-viewer/entity/mix/en/media/file/173
```json
{
"title": "Social Distancing Flyer in English",
"file": "/mnt/drupal-file/2020-03/3.11.20_Social_MultiLang_ENG.pdf",
"fid": "243",
"published": true,
"alt_text": "",
"description": "<p>Follow these recommendations from the San Francisco Department of Public Health to help reduce the spread of coronavirus (COVID-19) in the community.</p>\r\n",
"published_date": "2020-03-13"
},
```
```json
{
"title": "Social Distancing Flyer in English",
"file": "/app/web/sites/default/files/2020-03/3.11.20_Social_MultiLang_ENG.pdf",
"fid": "243",
"published": true,
"alt_text": "", …
```

CMS-697: Add the direct and indirect URL as a part of the payload for the Drupal API

---

web/modules/custom/sfgov_api/src/Plugin/SfgApi/Media/File.php
web/modules/custom/sfgov_api/src/Plugin/SfgApi/Media/Image.php

Add `drupal_indirect_path` and `drupal_direct_path` properties for media image serialization, too. Also changed media file to be in line as well.
https://sfgovdt.jira.com/browse/CMS-697

CMS-697: Add direct and indirect path for media_image
